### ISSUE TITLE
In classic WotLK  What setting turns on the prompts at holiday bosses?

### ISSUE THREAD

**Issue by maioro** [BigWigsMods/LittleWigs#1105]
## Describe the problem
1 - Can anyone tell me which setting or littlewigs or bigwigs addons are being used for the classic holiday boss tip? 
      just like - midsummer fire festival
     There are no boss skills or stage turn warnings after the start of the battle.
     and Now in 10.22.44 or 10.2.77  can't see anything in the bigwigs - Dungeon bosses option 
     choose the raid boss option results in a bigwigs error, but littlewigs doesn't report any errors.

### What steps will reproduce the problem?
BigWigs [Classic] --[v10.2.67]
BigWigs--[v328.5]  The above this version will get a lot of errors 。
LittleWigs--[v10.2.44] OR [v10.2.77]
### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![wlk 日期 2024-07-08](https://github.com/BigWigsMods/LittleWigs/assets/60441085/77fea9fb-e5bd-463e-9c64-9ea5e9ce8293)

![littlewigs-1](https://github.com/BigWigsMods/LittleWigs/assets/60441085/89e810eb-72b1-4223-b115-5f953314e228)

![littlewigs-2](https://github.com/BigWigsMods/LittleWigs/assets/60441085/02387439-4d01-49eb-b414-de32f3de49b0)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
3.4.3.55417  Wotlk-P1（China Server -  Wrath of the Lich King Classic Phase 2 - Ulduar It's not on yet , Perhaps on the 11th of July? ）
![wlk版本号](https://github.com/BigWigsMods/LittleWigs/assets/60441085/cb69b9bb-d172-47c6-9f33-3ded20a50d1f)
Free to Play all level Classic time 2024-06-27 —— 2024-07-10 
### Any additional information? (example: WoW language if not English)
English and chinese

**Comment by funkydude** [comment]
Why are you using old versions of BigWigs and LittleWigs? Update to the latest versions and everything will work fine.
You can find the options for the holiday boss in `Coilfang: The Slave Pens`
![image](https://github.com/BigWigsMods/LittleWigs/assets/16833/0db0216f-752c-42ee-8f0e-a70b21868d5c)

**Comment by maioro** [comment]
ok ok, no bugs in v341.
It's just in the Chinese servers reopened day, try the latest version had alot bugs ，then  went back to the old version.
Now everything is fine. thx

**Comment by funkydude** [comment]
Yes, a bug in the Chinese version was fixed 3 days ago thanks to a Chinese user reporting it to us. If you see more bugs, you need to report them to us. Please don't ignore them/use old versions. Thank you.
