### ISSUE TITLE
Little Wigs doesnt work 90% of the time

### ISSUE THREAD

**Issue by ardCOR3** [BigWigsMods/LittleWigs#1122]
## Describe the problem
Timers dont show 90% of the time.

### What steps will reproduce the problem?

1.  Do a cata dungeon, 
2.  Do a raid

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
4.40

Bigwigs, and littlewigs and cata are all installed

**Comment by ardCOR3** [comment]
LittleWigs-v11.0.6.zip

**Comment by funkydude** [comment]
Specify the exact boss and the exact abilities you are not seeing

**Comment by ardCOR3** [comment]
Hi its just not showing any ability for any boss. ive had it show for classic raid boss and thats it, 

Like it show a respawn timer, but shows nothing else. it worked in blackrock caverns

But its not showing in the stonecore and many others for me

**Comment by ardCOR3** [comment]
Am i doing something wrong?
what can i do?

**Comment by funkydude** [comment]
Please take some time and edit your post to add the exact boss and the exact ability you are expecting a timer for, but not seeing.

**Comment by ardCOR3** [comment]
![image](https://github.com/user-attachments/assets/3f99ac74-6a25-44d3-8b18-ce8ca41d22a2)
nothing went off for this boss

**Comment by ardCOR3** [comment]
also this boss 
![image](https://github.com/user-attachments/assets/184fcff9-5165-41a3-883f-3935519bbc6a)

**Comment by ardCOR3** [comment]
any many others

**Comment by ardCOR3** [comment]
am about to do Ozruk
but i doubt it will show

**Comment by ardCOR3** [comment]
It showed for Ozruk, but it only showed 1 out of the 5  
![image](https://github.com/user-attachments/assets/d49940f6-e141-4279-9f19-563282e21077)

**Comment by ardCOR3** [comment]
yet again nothing for 
![image](https://github.com/user-attachments/assets/6db35a9a-3966-4964-a20e-8c5d73cd1629)

**Comment by funkydude** [comment]
Show your UI during the boss, not the options.
Also, do you have BugSack and BugGrabber installed?

**Comment by ardCOR3** [comment]
i just reinstalled everything and removed saved variables.

**Comment by ardCOR3** [comment]
> Show your UI during the boss, not the options. Also, do you have BugSack and BugGrabber installed?

yes, well i get errors pop up all the time for other shit i dont even know so must have something

**Comment by funkydude** [comment]
We cannot help you resolve this problem if you don't follow the instructions. We didn't ask you to reinstall the addon, are you saying that solved the problem for you? If not, you're going to need to start providing the errors you see collected in the BugSack addon.

**Comment by ardCOR3** [comment]
complicated whilst in a dungeon group

**Comment by funkydude** [comment]
This isn't an instant messenger. Gather the information you need, and then reply.

As a reminder, you were asked the following:
1) Show a screenshot of your UI during the boss fight, clearly displaying the missing bars.
2) Install the BugSack and BugGrabber addons and provide us with any errors you were receiving.

**Comment by ardCOR3** [comment]
Your addon is always asking me to install other modules i dont want, like capper, and now bugsack, when i dont need any of it, i already told you no bugs have popped up. Bigwigs is showing spells in the  bosses, that arnt showing timers on the screen, dont know what more you want me to do, not every problem gives a bug, you should know that. i cant ask on curse comments so where else am i supposed to  ask questions?

**Comment by funkydude** [comment]
We are trying to help you resolve a problem only you are having, that requires you to follow instructions so that we can help you.

The instructions are not complex, you have been asked for a screenshot, and you have been asked to install an addon that catches errors, because Blizzard doesn't show errors by default.

If you do not follow the instructions this issue will be closed.
