### ISSUE TITLE
Necrotic Wake error

### ISSUE THREAD

**Issue by Kainie85** [BigWigsMods/LittleWigs#1127]
## Describe the problem
Getting this error in Mythic 0 of Necrotic Wake

### What steps will reproduce the problem?

1.  I think the error happens on the 2 Skeletal Marauder's after the bridge between first and second boss
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
11.0.12

### Do you have an error log of what happened?
2x ...Ons/LittleWigs_Shadowlands/TheNecroticWake/Trash.lua:384: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@LittleWigs_Shadowlands/TheNecroticWake/Trash.lua"]:384: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:735: in function <BigWigs_Core/BossPrototype.lua:693>

Locals:
(*temporary) = "%s on %s"
(*temporary) = "Boneshatter Shield"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/5bcbc83d996f1f20f579ce53f30d8c1185d4fc1a, thank you for reporting!
