### ISSUE TITLE
[request] custom message

### ISSUE THREAD

**Issue by noelheesen** [BigWigsMods/LittleWigs#1143]
## The Pain

Quite often it's more convenient to see what's going to happen to you than the name of the ability which you can already see in the bar as well. It's getting more and more common to have weakauras read bigwigs timers to create custom messages, just like in Atrocity UI. It seems like something that belongs in LittleWigs. 

![image](https://github.com/user-attachments/assets/a86b9f26-55a3-4141-8099-f6cd8df5a097)
![image](https://github.com/user-attachments/assets/b78ccf7d-46aa-4bcd-8d23-9e67a04e9996)

### The Solution

I propose adding a new tab `messages` where you can toggle a custom message with an input for the message.
if a custom message is activated then maybe it should overwrite the default message to avoid conflicts and clutter?

![image](https://github.com/user-attachments/assets/be9169c2-1969-44b0-8585-e4715abd7a30)

I would be willing to help this proposal take shape if nobody has time.

**Comment by funkydude** [comment]
LittleWigs is a content addon for BigWigs, no such features exist in it, only boss modules.

With regards to the actual request, renames are hard coded. If you want something renamed, just request it.

About customizability, this is on the roadmap for a future BigWigs update, thanks!
