### ISSUE TITLE
Shadowlands LittleWigs Missing

### ISSUE THREAD

**Issue by KravenSkittlez** [BigWigsMods/LittleWigs#1161]
## Describe the problem
Last update nuked shadowlands duns out of the littlewigs boss list

### What steps will reproduce the problem?

1.  Update LittleWigs
2.  Launch Game
3.  Enter Shadowlands M+ Dungeon

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/user-attachments/assets/af4922c9-4be0-42ce-8f86-6e1a91be79c8)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v11.0.34

**Comment by funkydude** [comment]
Click on shadowlands and read what it says

**Comment by KravenSkittlez** [comment]
![image](https://github.com/user-attachments/assets/452f23bc-54b3-41a2-8ca0-223e50db1da0)
![image](https://github.com/user-attachments/assets/dbe6c336-5a72-4ab6-878a-5e9639605908)

**Comment by KravenSkittlez** [comment]
rolled back to .33 and they're back
![image](https://github.com/user-attachments/assets/70bc6f27-9250-4184-a6f9-be9f36199aa7)

**Comment by funkydude** [comment]
What method are you using to update?

**Comment by KravenSkittlez** [comment]
CurseForge

**Comment by funkydude** [comment]
Please be descriptive in your responses and do not provide 1 word replies.

Curseforge what? Downloading from the curseforge website? The curseforge official app?

If it's the app, show a screenshot of it installed.

**Comment by KravenSkittlez** [comment]
![image](https://github.com/user-attachments/assets/3c05952c-e62a-4642-b712-e2fa548740c7)

**Comment by funkydude** [comment]
Does the issue return if you update again?

**Comment by KravenSkittlez** [comment]
![image](https://github.com/user-attachments/assets/409718b0-0929-4878-aaa8-e036939563c3)
It did not. I guess it was a one time fluke. sorry for the waste of time.

**Comment by funkydude** [comment]
Assuming you didn't close the app whilst it was still updating, you likely have corruption issues unfortunately. Likely from 3rd party security software or a bad/near full disk drive.
