### ISSUE TITLE
Chopper Redhook - Iron Hook ability missing from Redhook abilities list

### ISSUE THREAD

**Issue by xFreddx** [BigWigsMods/LittleWigs#1164]
Chopper Redhook's Iron Hook ability does not appear in the abilities list in the LittleWigs Dungeon Boss abilities list.

### What steps will reproduce the problem?

1.  Open BigWigs settings
2.  Switch to the Dungeon Bosses Tab
3.  Select "Siege of Boralus"
4. Select Chopper Redhook in the Boss Selection Dropdown menu
5. Notice that the "Iron Hook" ability is missing.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![Redhook - Missing Iron Hook Ability](https://github.com/user-attachments/assets/67c3b651-a0fb-4108-a60b-31a52a858a14)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)

v11.0.39

### Do you have an error log of what happened?

No

### Any additional information? (example: WoW language if not English)

This issues appears on other boss abilities lists. Would recommend doing a thorough review and some point early in the season.

**Comment by xFreddx** [comment]
Additionally the Bilge Rat Pillager and its abilities are missing from the trash abilities list.

![Pillager Missing](https://github.com/user-attachments/assets/bff521ea-8782-47ff-b330-dc2d100a7a24)

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/07516cbb2d59041bb0abc8f1b5c5e7b8695122c9 and https://github.com/BigWigsMods/LittleWigs/commit/29e4945e11fc8be462bfdb942ac4838fbf9398bc.
