### ISSUE TITLE
FPS drops / frametime issues since v11.0.42

### ISSUE THREAD

**Issue by sixsi** [BigWigsMods/LittleWigs#1173]
I get frametime spikes since v11.0.42 update. If i roll back to v11.0.41 it's fine.

1.  Update the addon to the latest version (v11.0.42 or higher).
2.  Start any M+ or dungeon content.
3.  Notice frametime / fps spikes in combat.

Appears on v11.0.42 and higher

No errors.

Client language: English.

**Comment by funkydude** [comment]
You've not shown any evidence in the form of CPU profiling to prove this is LittleWigs. You've just made an assumption. 

Please do actual CPU profiling. Alternately if you have BugSack installed and you're sure there's no errors, you can try running a follower dungeon with only BigWigs and LittleWigs enabled, nothing else.

**Comment by funkydude** [comment]
No response, closing.
