### ISSUE TITLE
Right Click bug with this addon.

### ISSUE THREAD

**Issue by Snugglepaw** [BigWigsMods/LittleWigs#1210]
## Describe the problem
Ive noticed that when this addon is turned on there are spots on my screen where when I right click and hold my cursor does not go away and I can't rotate my camera.

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Unless you are specifically seeing tooltips to indicate it's BigWigs, then it isn't. You can use `/fstack` to debug such issues.
