### ISSUE TITLE
Timer update of Ki'katal the Harvester of Ara-Kara

### ISSUE THREAD

**Issue by Rubgrsch** [BigWigsMods/LittleWigs#1211]
## Describe the problem
The timers of Ki'katal the Harvester in Ara-Kara (mythicpluis version) are really a mess. Following info are extracted and analysised from a random [combatlog](https://www.warcraftlogs.com/reports/avQbJRxP78nL3T94#fight=last&start=2440830&end=2713066&type=casts&view=events).

### What steps will reproduce the problem?

Initial cast after engaging
- Erupting Webs: 6.5
- Cultivated Poisons: 12.6
- Cosmic Singularity: 28.4

Skill cd (after the first)
- Erupting Webs: 18.2
- Cultivated Poisons: 21.8
- Cosmic Singularity: 46.1

If boss starts casting **Cosmic Singularity**, following will be delayed to at least:
- Erupting Webs: 7.3
- Cultivated Poisons: 13.3

Which means, new timer = max(old timer, ^this value^).

### Attach a screenshot below to help describe your issue (Attach directly, do not link to other websites)
nope

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v11.0.52

### Do you have an error log of what happened?
nope

### Any additional information? (example: WoW language if not English)
nope

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/6fc3e487614c1b372b42ac93d2c11fd3e78b870b, thanks for the report.
