### ISSUE TITLE
Infestation timer on Anubzekt doesn't work?

### ISSUE THREAD

**Issue by wwbrandon** [BigWigsMods/LittleWigs#1212]
hey, unless the cast isn't on a strict timer... BW isn't queuing the timer for the attack--
Only important spell there!

**Comment by ntowle** [comment]
It's such a short cooldown (10.5s in stage 1, 8.1s in stage 2) with such a high variance (up to ~30s between casts on the right ability queue) that I didn't think it was particularly worth tracking, especially given that it goes on a random player so you can't prepare for it.

I had the timer enabled during beta but it ended up seeming like clutter in practice so I removed it.

**Comment by wwbrandon** [comment]
pushing into 16s as a Disc Priest it's really the only critical timer to track if you ask me. Additionally, there are things I need to do to prepare for it, and if I don't ramp in time, it can be a disaster.

It's the only timer on that boss I'd even have enabled

**Comment by ntowle** [comment]
Added an Infestation bar for healers in https://github.com/BigWigsMods/LittleWigs/commit/81b3374dc9d0b7f3a9f622688ffbdcbef6775679.

**Comment by wwbrandon** [comment]
Appreciate it :D
