### ISSUE TITLE
Ularogg Cragshaper

### ISSUE THREAD

**Issue by yesCurtis** [BigWigsMods/LittleWigs#18]
The idol marker that was added on January the 3rd, is now broken since 7.1.5 has hit. It's no longer working, not sure if it's the actual full thing not working or if it's just in mythic+.

Running 7-9 keys and it no longer auto marks, I have tried a WA for auto-marking them aswell but this no longer works, so I'm assuming they have changed the way the idols spawn or something.

**Comment by elvador** [comment]
Yeah, they've hidden the SPELL_SUMMON events for the totems. There might be other ways to track the correct totem, but I'll have to confirm them in game first.
