### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by mixMugz** [BigWigsMods/LittleWigs#312]
How i can edit LW options? Such prefix in chat like [littlewigs]? 

Trying /lw, /littlewigs, /little - but with no luck.

**Comment by nebularg** [comment]
/bw to open the main BigWigs options then click on the "Dungeon Bosses" tab

**Comment by mixMugz** [comment]
Ohh. IN BW I don't see any option to setup Infobox (Locking for example) and cant remove [Littlewigs] prefix whent addon posting in chat.
