### ISSUE TITLE
Since 3-4 days Littlewigs isn't announcing 10% of what its supposed to announce.

### ISSUE THREAD

**Issue by polki92** [BigWigsMods/LittleWigs#323]
Hello.

Since a few days ( my bigwigs and littlewigs are up to date ) I have issues with littlewigs in BFA dungeons.

I used to see everything I wanted to see during every boss fights ( I checked all abilities I want to see an announce for, in the options panel ) but now it's all completely random.

On the same boss, I'm sometimes getting no announce, or randomly announced skills.

For example on Merekpha, 2nd boss of Sephraliss Temple, I used to announce on voice chat everything like 5sc before they happen : the poison breath, the blinding sand.... for my team to prepare.

Now I can't announce anything, no bar are showing. And this happens for almost every bosses.
Sometimes only 1 breath is showing during the fight.
Sometimes the breath isn't announced but a bar is displaying the boss casting the poison breath like 
" < poison breath is being casted > "  instead of " Poison breath in 5sc "

I haven't installed any addons since like a week and haven't changed anything in Littlewigs config panel.

Thanks in advance for your help :)

**Comment by polki92** [comment]
@funkydude nobody's here?

**Comment by Zireael-N** [comment]
To be able to help you, we need a little bit more of information:

1) Do you have similar issues with only BigWigs + LittleWigs enabled?
2) Could you please install an addon that captures Lua errors (alternatively, you can use `/console scriptErrors 1` to enable the built-in error display, but it's intrusive), like BugSack, and check whether there are any errors?

**Comment by polki92** [comment]
Well thanks for your reply.

If it's only me having issues with 0.13 i'll just check on my side :)

But it's strange that it just came without any newly installed addons, nor anything.

Plus, I only use very known addons such as Elvui, Kui, Weakauras, TsM. So I doubt it comes from them and I know they don't have conflict issues with BigWigs or LittleWigs
