### ISSUE TITLE
LittleWigs Freehold Ring of Bounty - Pig timer doesn't show anymore

### ISSUE THREAD

**Issue by Sdanx** [BigWigsMods/LittleWigs#333]
Hi, title says it all. I've tried reloading, tick and un-tick the setting, de-activate then reactivate Little Wigs but it still doesn't show.

Thanks!

**Comment by Sdanx** [comment]
@funkydude Maybe it never happened, I may be crazy, but I really think there used to be a timer bar for WHEN the pig would spawn. How long the event is.

Now, there is indeed like you say a message after you've captured it but I was talking about a bar / timer telling us when the pig is about to spawn. It's useful to know, especially for filling the trash % account during the time the npcs are talking.

**Comment by Justw8** [comment]
This timer does not exist (yet), there's only one for the actual boss after you defeat the turtle right now.

**Comment by Justw8** [comment]
added with https://github.com/BigWigsMods/LittleWigs/commit/8356f4ee1fb016f3fd51615d08908007fc4b73c3
