### ISSUE TITLE
The option to disable "autotalk" in Court of Stars is missing

### ISSUE THREAD

**Issue by Dusky34** [BigWigsMods/LittleWigs#334]

**Comment by funkydude** [comment]
Are you talking about the spy event? It's part of the spy helper option. There is no separate option just for the auto talking.

**Comment by AntoineBann** [comment]
Sorry I should have provided a description. 
For this dungeon there is an option to disable the setting that makes you instantly use the various buffs upon clicking them, but you can't disable the more "usual" autotalk feature like for the lantern dialog at the start of the dungeon.
In the trash.lua file for the CoS dungeon there are 3 entries in the "Autotalk" block :

[107486] = true, -- Chatty Rumormonger
[106468] = true, -- Ly'leth Lunastre
[105729] = true, -- Signal Lantern: Boat at the start

There doesn't seem to be an option that lets you disable Autotalk for those 3 events.
There is an option to disable Autotalk for every other dungeon encounter/trash lua file that includes the feature except for this dungeon.

There are 11 instances of this setting currently:

- Trash in Trial of the Champion (WotLK)
- Trash in The Culling of Stratholme (WotLK)
- Trash in Well of Eternity (Cataclysm)
- Ozumat in Throne of the Tides (Cataclysm)
- Vojak in Siege of Niuzao Temple (MoP)
- Trash in Assault on Violet Hold (Legion)
- Odyn in Halls of Valor (Legion)
- Trash in Halls of Valor (Legion)
- Trash in Karazhan (Legion)
- Domatrax in Cathedral of Eternal Night (Legion)
- Trash in Seat of the Triumvirate (Legion)

Please let me know if you want any additional information.

**Comment by funkydude** [comment]
It's unlikely this will change at this point.
