### ISSUE TITLE
Shrine of the Storm : add a trash pack guide

### ISSUE THREAD

**Issue by FunkySayu** [BigWigsMods/LittleWigs#335]
I can take this one.

There is a missing registry for trash packs in Shrine of the Storm. These trash have some important kick abilities, such as Mending rapid (among others) that should be raised by LittleWigs.

If you are willing to let me take it, I'll base my work on [WoWHead guide for SOTS](https://www.wowhead.com/guides/shrine-of-the-storm-dungeon-strategy-guide)-

**Comment by Justw8** [comment]
Feel free to make a pull request.

**Comment by FunkySayu** [comment]
Sure, let me a bit of time to get used to lua and I'll make a PR :)

**Comment by funkydude** [comment]
>Any chance you can add a non crazy restrictive license file to your repo?

No. We're not really looking for contributions on behalf of companies, it's just a wow addon.

**Comment by FunkySayu** [comment]
Sure, though it's not a contribution on behalf of a company. Sorry if I appeared to be rude.

Basically, [lack of licenses technically denies use, modification and sharing of the code](https://choosealicense.com/no-permission/) which is a bit dangerous for contributors.

>If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
>
>Your options:
>Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site, or if you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license.

As per my contract, my company is asking to review the license of any open source project we want to contribute to to avoid contribution to non-licensed / too intrusive licenses (there are some crazy stuff in some licenses).

**Comment by funkydude** [comment]
We do have a license: https://github.com/BigWigsMods/LittleWigs/blob/8356f4ee1fb016f3fd51615d08908007fc4b73c3/LittleWigs.toc#L18

i.e. we reserve the right to decide everything on an individual basis.
That's not going to change.

**Comment by FunkySayu** [comment]
I'm afraid I cannot contribute then :( Not having a standard license makes it possible for all sorts of legal attack.

If you happen to change your mind, feel free to ping me! I'm letting open this bug since it is related to the mod itself.

**Comment by funkydude** [comment]
Would a clause that protects you from all liability make you comfortable with contributing?

**Comment by FunkySayu** [comment]
I'm not sure for the details, but that'll probably be quite a headache.

Any reasons that is an issue? I am quite open to any kind of licences (as long as it is not too intrusive, some licenses imply any code written by the contributor, **in or outside the project**, is owned by the project owner...)

**Comment by FunkySayu** [comment]
Sorry to be boring about this one, I've been told to be really careful about this :(

**Comment by funkydude** [comment]
I was just guessing that your main issue was you didn't feel protected from liability. Since that's not the case we'll just leave it as is. Thanks for your time.
