### ISSUE TITLE
New error after updating today

### ISSUE THREAD

**Issue by MikeRixWolfe** [BigWigsMods/LittleWigs#338]
After spam clicking the pig in freehold

Message: ..\AddOns\LittleWigs\BfA\Freehold\Booty.lua line 136:
   attempt to call method 'PlayVictorySound' (a nil value)
Debug:
   LittleWigs\BfA\Freehold\Booty.lua:136: ?()
   BigWigs_Core\BossPrototype.lua:445:
      BigWigs_Core\BossPrototype.lua:411

**Comment by funkydude** [comment]
Requires the latest BigWigs, which has now been released.
