### ISSUE TITLE
Auto Accept npc dialog in instance

### ISSUE THREAD

**Issue by Shaldarax** [BigWigsMods/LittleWigs#385]
Hi, 

How to disable the option that auto accept dialog with the npc's in instance? (for exemple talking mage at the start of Violet Hold).
 
It's embarrassing because I want to read the dialogues. The problem comes from BW / Little wigs.

**Comment by Zireael-N** [comment]
![image](https://user-images.githubusercontent.com/13710677/46739945-50fc0380-ccaa-11e8-850f-3109f6c51117.png)

**Comment by Shaldarax** [comment]
Thank you!
