### ISSUE TITLE
Separate each expansion into different module to reduce loading time

### ISSUE THREAD

**Issue by Rubgrsch** [BigWigsMods/LittleWigs#390]

**Comment by penguinsane** [comment]
Did this ever get pushed to the addon? When I have LittleWigs enabled, I still get tremendous load times - upwards of 1-2 minutes on a SSD even - on first load of a dungeon each day. I'm desperate to solve this, I love BigWigs/LittleWigs so much, but I need timers in dungeons.

**Comment by funkydude** [comment]
It will be done prior to the expansion opening.
