### ISSUE TITLE
Lua Error on Heroic Seat of the Triumvirate Viceroy Neshar

### ISSUE THREAD

**Issue by Ramurotand** [BigWigsMods/LittleWigs#419]
Message: Interface\AddOns\BigWigs_Core\BossPrototype.lua:939: attempt to call field '?' (a nil value)
Time: Wed Feb 20 09:27:09 2019
Count: 9
Stack: Interface\AddOns\BigWigs_Core\BossPrototype.lua:939: attempt to call field '?' (a nil value)
Interface\AddOns\BigWigs_Core\BossPrototype.lua:939: in function `?'
Interface\AddOns\BigWigs_Core\Core.lua:59: in function <Interface\AddOns\BigWigs_Core\Core.lua:54>

Locals: self = <table> {
 CHAT_MSG_MONSTER_YELL = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:76
 instanceId = 1753
 RegisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:897
 UnregisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:918
 colorOptions = <table> {
 }
 soundOptions = <table> {
 }
 MarkMatter = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:100
 PersonalAurasWithSay = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:82
 GOSSIP_SHOW = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:111
 VoidDiffusionCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:89
 toggleOptions = <table> {
 }
 OnBossEnable = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:59
 optionHeaders = <table> {
 }
 RegisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:64
 toggleDefaults = <table> {
 }
 db = <table> {
 }
 displayName = "Trash"
 SendMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:931
 name = "BigWigs_Bosses_Seat of the Triumvirate Trash"
 CollapseCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:107
 localization = <table> {
 }
 moduleName = "Seat of the Triumvirate Trash"
 UnregisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:71
 DarkMatterCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:93
}
event = "NAME_PLATE_UNIT_ADDED"
unit = "nameplate6"
guid = "Creature-0-3779-1753-4918-122827-00016D71C9"
(*temporary) = nil
(*temporary) = <table> {
 CHAT_MSG_MONSTER_YELL = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:76
 instanceId = 1753
 RegisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:897
 UnregisterMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:918
 colorOptions = <table> {
 }
 soundOptions = <table> {
 }
 MarkMatter = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:100
 PersonalAurasWithSay = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:82
 GOSSIP_SHOW = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:111
 VoidDiffusionCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:89
 toggleOptions = <table> {
 }
 OnBossEnable = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:59
 optionHeaders = <table> {
 }
 RegisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:64
 toggleDefaults = <table> {
 }
 db = <table> {
 }
 displayName = "Trash"
 SendMessage = <function> defined @Interface\AddOns\BigWigs\Loader.lua:931
 name = "BigWigs_Bosses_Seat of the Triumvirate Trash"
 CollapseCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:107
 localization = <table> {
 }
 moduleName = "Seat of the Triumvirate Trash"
 UnregisterEvent = <function> defined @Interface\AddOns\BigWigs_Core\Core.lua:71
 DarkMatterCast = <function> defined @Interface\AddOns\LittleWigs\Legion\SeatOfTheTriumvirate\Trash.lua:93
}
(*temporary) = "NAME_PLATE_UNIT_ADDED"
(*temporary) = "nameplate6"
(*temporary) = "Creature-0-3779-1753-4918-122827-00016D71C9"
(*temporary) = "attempt to call field '?' (a nil value)"
UnitGUID = <function> define

**Comment by funkydude** [comment]
Unfortunately this error is useless. It looks like it's been cut out and is probably a follow up error to the real error. Please use the [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon for collecting errors in future.
