### ISSUE TITLE
Lua Error on Heroic Seat of the Triumvirate Viceroy Neshar

### ISSUE THREAD

**Issue by Ramurotand** [BigWigsMods/LittleWigs#420]
In this ticket (https://github.com/BigWigsMods/LittleWigs/issues/419) you said to run bugsack/buggrabber so here's the info from that.  Replicated this every day for weeks now on a level 120 Horde Retribution Paladin.  This did not occur when I ran it on a level 120 Horde Windwalker Monk.  It does not occur on Mythic Seat of the Triumvirate Viceroy Neshar.

10x BigWigs_Core\BossPrototype.lua:939: attempt to call field '?' (a nil value)
BigWigs_Core\BossPrototype.lua:939: in function `?'
BigWigs_Core\Core.lua:59: in function <BigWigs_Core\Core.lua:54>

Locals:
InCombatSkipped

22x BigWigs_Core\BossPrototype.lua:926: attempt to call field '?' (a nil value)
BigWigs_Core\BossPrototype.lua:926: in function `?'
BigWigs_Core\Core.lua:59: in function <BigWigs_Core\Core.lua:54>

Locals:
InCombatSkipped

21x BigWigs_Core\BossPrototype.lua:919: attempt to call field '?' (a nil value)
BigWigs_Core\BossPrototype.lua:919: in function `?'
BigWigs_Core\Core.lua:59: in function <BigWigs_Core\Core.lua:54>

Locals:
InCombatSkipped

**Comment by funkydude** [comment]
Thanks. This has nothing do with LittleWigs and is actually a core issue.
It has been fixed in https://github.com/BigWigsMods/BigWigs/commit/f453bc7aea879b16a39f61ed0b0826465ff601cd and will be in the next release.
