### ISSUE TITLE
Dungeons crash trying to load in

### ISSUE THREAD

**Issue by Polarthief** [BigWigsMods/LittleWigs#450]
Small sample size, but I may have isolated an issue of mine with crashing while queuing for some  BC/LK dungeons with LittleWigs.

The following dungeons I've crashed trying to get into via LFD: Halls of Lightning (twice), Steamvault, Mechanar, Black Morass. Prior to testing addons, I didn't get into any of these dungeons successfully once.

After turning off JUST LittleWigs, my very next Steamvault worked fine. I then logged off, turned LittleWigs back on, and my very next queue was Black Morass, which crashed me upon the first frame of the dungeon (if I try to relogin, it instead tends to crash at ~20% of the loading screen bar). I then relogged in, but turned off LittleWigs before picking my character, worked perfectly.

I didn't get into every Vanilla, BC, and LK dungeon, but I didn't have a single issue in Vanilla and I leveled from 20-78 so far exclusively through dungeons, so I went through quite a few of them. Vanilla I had LittleWigs turned on the entire time, and same with BC/LK until these crashes started happening around 2 days ago.

I intend to keep leveling this alt of mine via dungeons, will report back on any more dungeons that crash, and specifically if turning off LittleWigs (and ONLY LittleWigs) fixes the issue.

Edit: Entered Magister's Terrace just fine with LW off, turned it on and it crashed, turned it back off and all was fixed.
Edit: Also Oculus. At this point, I just have LW turned off and I'm not crashing at all.
Edit: It's now affected BfA dungeons too. Couldn't get in my M+ Tol Dagor group without disabling LittleWigs first.

**Comment by funkydude** [comment]
Have you tested with ONLY BW & LW? If it works I suggest you try to find out what combination of addons is the cause.

**Comment by funkydude** [comment]
No response, closing.
