### ISSUE TITLE
Mechagon HARDMODE timer

### ISSUE THREAD

**Issue by MrSlavaa** [BigWigsMods/LittleWigs#476]
Hello, please help me. When i go harmode mechagon, i see bar+timer on hardmode only on first time after finish first hardmode i not see next timers and bars on harmode. 
Test: delete every setings and addons install only LittleWigs and nothing.
Test: install DBM and in DBM is good timers i see all phase.
![WoWScrnShot_081419_232327](https://user-images.githubusercontent.com/54123634/63061912-2cd70780-bef7-11e9-9346-d90500b8f77f.jpg) Here we see in P1 first Hardmode timer on pull
![WoWScrnShot_081419_232452](https://user-images.githubusercontent.com/54123634/63061920-3b252380-bef7-11e9-91d0-512743292251.jpg) this 2nd screan is after firts compelete harmode and not up new timer and bar

And same problem my 2 friends in LittleWigs.

How is chance fix it pls? :(

**Comment by funkydude** [comment]
We cannot reproduce this problem. Are you sure you're actually using the latest version of LittleWigs?

**Comment by MrSlavaa** [comment]
im 100% used last version.. im delete all seting all addons and testing only last version and nothing.. Same problem my 2 friends.. next friends not problem.

**Comment by funkydude** [comment]
I have confirmed it is 100% working fine. You can also go on YouTube and watch videos of people doing it with LittleWigs, and the timer is working fine.

You are most likely getting some form of error, so install the `BugSack` addon to collect them.

**Comment by funkydude** [comment]
No response, closing.
