### ISSUE TITLE
Invalid spell ID 93581,93423,93757

### ISSUE THREAD

**Issue by martinsir** [BigWigsMods/LittleWigs#484]
I am getting these error's in Shadowfang Keep.
---------------------------------------------------------------------------------------------------------
BigWigs: Invalid spell ID 93581 in the toggleOptions for module BigWigs_Bosses_Baron Ashbury. 
BigWigs: Invalid spell ID 93423 in the toggleOptions for module BigWigs_Bosses_Baron Ashbury. 
BigWigs: Invalid spell ID 93757 in the toggleOptions for module BigWigs_Bosses_Baron Ashbury. 
BigWigs: Invalid option 93581 in module BigWigs_Bosses_Baron Ashbury. 
BigWigs: No spell description was returned for id 93581! 
BigWigs: Invalid option 93423 in module BigWigs_Bosses_Baron Ashbury. 
BigWigs: No spell description was returned for id 93423! 
BigWigs: Invalid option 93757 in module BigWigs_Bosses_Baron Ashbury. 
BigWigs: No spell description was returned for id 93757!

Date: 2019-09-25 18:30:03
ID: 1
Error occured in: Global
Count: 1
Message: Invalid spell ID 93581 in the toggleOptions for module BigWigs_Bosses_Baron Ashbury.
Debug:
   BigWigs_Core\Core.lua:602:
      BigWigs_Core\Core.lua:535
   BigWigs_Core\Core.lua:623: SetupOptions()
   BigWigs_Options\Options.lua:980:
      BigWigs_Options\Options.lua:844
   BigWigs_Options\Options.lua:1006:
      BigWigs_Options\Options.lua:1003
   [C]: ?
   ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...AceGUI-3.0\widgets\AceGUIContainer-DropDownGroup.lua:66: SetGroup()
   BigWigs_Options\Options.lua:1061:
      BigWigs_Options\Options.lua:1009
   BigWigs_Options\Options.lua:1099:
      BigWigs_Options\Options.lua:1095
   [C]: ?
   ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ddOns\AddOnSkins\Libs\Ace3\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...ce3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:515: SetSelected()
   ...ce3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:191:
      ...ce3\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:187
Locals:
None
----------------------------------------------------------------------------------

Date: 2019-09-25 15:09:56
ID: 2
Error occured in: Global
Count: 1
Message: Invalid spell ID 93687 in the toggleOptions for module BigWigs_Bosses_Commander Springvale.
Debug:
   BigWigs_Core\Core.lua:602:
      BigWigs_Core\Core.lua:535
   BigWigs_Core\Core.lua:623: SetupOptions()
   BigWigs_Core\BossPrototype.lua:225: Enable()
   BigWigs_Core\Core.lua:118:
      BigWigs_Core\Core.lua:116
   BigWigs_Core\Core.lua:129:
      BigWigs_Core\Core.lua:125
   BigWigs_Core\Core.lua:135:
      BigWigs_Core\Core.lua:133
   BigWigs_Core\Core.lua:149:
      BigWigs_Core\Core.lua:144
   BigWigs_Core\Core.lua:155: v()
   BigWigs_Core\Core.lua:56:
      BigWigs_Core\Core.lua:53
Locals:
None
-----------------------------------------------------------------------------------
Date: 2019-09-25 15:06:53
ID: 1
Error occured in: Global
Count: 1
Message: Invalid spell ID 93857 in the toggleOptions for module BigWigs_Bosses_Baron Silverlaine.
Debug:
   BigWigs_Core\Core.lua:602:
      BigWigs_Core\Core.lua:535
   BigWigs_Core\Core.lua:623: SetupOptions()
   BigWigs_Core\BossPrototype.lua:225: Enable()
   BigWigs_Core\Core.lua:118:
      BigWigs_Core\Core.lua:116
   BigWigs_Core\Core.lua:129:
      BigWigs_Core\Core.lua:125
   BigWigs_Core\Core.lua:135:
      BigWigs_Core\Core.lua:133
   BigWigs_Core\Core.lua:149:
      BigWigs_Core\Core.lua:144
   BigWigs_Core\Core.lua:155: v()
   BigWigs_Core\Core.lua:56:
      BigWigs_Core\Core.lua:53
Locals:
None
----------------------------------------------------------------------------------------------
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AddOnSkins, v4.31
  AtlasLootClassic, vv1.1.12
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.13
  BagnonConfig, v
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BigWigs, vv3-classic
  BigWigsCore, v
  BigWigsOptions, v
  BigWigsPlugins, v
  ClassicSpellActivations, v
  Clique, vv1.0.3-classic
  Details, v
  DetailsTinyThreat, v
  ElvUI, v1.09
  ElvUIExtraDataTextsClassic, v1.0.2
  ElvUILocationPlus, v1.00
  ElvUIOptionsUI, v1.06
  GTFO, v4.49.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesElite, vv1.0-classic
  LeatrixMaps, v1.13.32
  LibSharedMedia30, v3.0-113
  LittleWigs, vv1-classic
  NugEnergy, v1.13.10
  Questie, v4.1.1 BETA
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11302-1.0.7
  VendorPrice, v1.2.6
  WeakAuras, v2.15.0
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=4f2)

**Comment by vendethiel** [comment]
Is this fixed in the last commit?
