### ISSUE TITLE
Horrific Vision Orgrimmar - Thrall hard mode abilities

### ISSUE THREAD

**Issue by constancecchen** [BigWigsMods/LittleWigs#510]
By "hard mode abilities" I mean the abilities he gains after clearing a lost area (see https://www.wowhead.com/guides/horrific-vision-of-orgrimmar-strategy-guide#tab-vosabilties-thrall).

In particular the ability missing is when he starts using Defiled Ground instead of Seismic Slam. LittleWigs no longer correctly warns/shows timers for that ability (spell ID 306726). Would super appreciate it if that could get added to LittleWigs - I sorely need an airhorn in my life whenever that's going off :)

**Comment by Oppzippy** [comment]
Thanks for the suggestion, added.

**Comment by constancecchen** [comment]
Thanks so much, y'all rock! Looks like I may have gotten the spell ID wrong as well, apologies if so!
