### ISSUE TITLE
Littlewigs

### ISSUE THREAD

**Issue by Luusee** [BigWigsMods/LittleWigs#525]
I use this addon for mythic plus dungeons in World of Warcraft. Suddenly last week Littlewigs stopped working on one particular boss in Atal'Dazar. Vol'kaal.  Littlewigs would place 3 totem bars on the screen. 3 DPS would each kill one of the totems having them all die at the same time. Last week it stopped putting those 3 essential bars on the screen. I checked my computer; uninstalled and reinstalled Bigwigs and Littlewigs; made sure everything was up to date etc.  Nothing fixed the problem . I attempted 3 more different mythic plus Atal'Dazars all with the same fail outcome.  It is a liability for me not to have that addon working when i join an Atal group. I have cause 3 disbands and the leaders have lost their key. So what is going on? Is Littlewigs no longer supported? Please tell me if you can fix it or I will have to find another addon. I have been playing Wow since 2004 and i prefer Bigwigs to DBM.

**Comment by nebularg** [comment]
LittleWigs has never shown any bars for the totems, so you probably had a WeakAura for it

**Comment by Zireael-N** [comment]
You can see their HP on your boss frames.

**Comment by Luusee** [comment]
I never downloaded anything from weak auras to assist with Vol’kaal it was always auto that is why I believe it is related to Bigwigs/Littlewigs


Sent from Mail for Windows 10

**Comment by Luusee** [comment]
Never have downloaded a weak aura for anything related to any dungeon at all. I have no idea what this problem is or how to fix it.   I know a weak aura exists.  But that is not the issue.  The issue is the 3 totem health bars always auto appeared without me downloading anything ever.

Sent from Mail for Windows 10

**Comment by nebularg** [comment]
I don't know what to tell you, LittleWigs has never never shown health bars, so something else changed.

**Comment by Luusee** [comment]
You are correct; my boss frames had disappeared and for some unknown reason SMART RAID FILTER was checked…not by me I leave Elvui alone …that filter made them disappear.  Thank you for pointing me in the correct direction.

Sent from Mail for Windows 10

**Comment by Luusee** [comment]
You are correct after much  digging it became apparent that it was Elvui interfering.  I can only say when something goes wrong it takes quite awhile to figure out and a lot of material to dig through to find and correct that problem.  Thank you.

Sent from Mail for Windows 10
