### ISSUE TITLE
Allow us to choose which announcements we want to hide/show

### ISSUE THREAD

**Issue by MrAntrophy** [BigWigsMods/LittleWigs#531]
I know you can filter certain spells but what I mean is interrupt announcing. Namely the _**{Boss ability} was interrupted by {person name}**_ is really useless to show (for some people) as you have nameplates that do this or you have chat announcers for that. It also clutters a screen as it's not that important who interrupted it. Either add it to each spell separately or global disable (or both, which is better).

![Capture](https://user-images.githubusercontent.com/34379991/89924110-d67fd000-dc01-11ea-870e-181e27c22e75.JPG)

**Comment by nebularg** [comment]
That is used just once this expansion and it's for Motivating Cry. Not everyone has something that announces interrupts and it's useful to see if someone interrupted it unexpectedly.
