### ISSUE TITLE
BFA: Shrine of the Storm

### ISSUE THREAD

**Issue by FireAllianceNX** [BigWigsMods/LittleWigs#538]
Not sure if this is enough information, let me know if you need more.

1x Void seed applied: count: 2, duration: 12, previous max duration: 1. Tell the authors!
[string "@LittleWigs\BfA\ShrineOfTheStorm\Trash.lua"]:295: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:489: in function <BigWigs_Core\BossPrototype.lua:455>

**Comment by ntowle** [comment]
Fixed by e73f8f2aee12115e38834844095c5ba3a8a3bee3.
