### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by Sacuri** [BigWigsMods/LittleWigs#539]
Maybe im just dumb But some Alerts are in english and some in German and i Want only German But have no idea how to fix That . 

So is it just me or are not all translate  to German in the Current Version ?

**Comment by funkydude** [comment]
If things are appearing in English, it simply means they haven't been translated. Every dungeon has its own locale files.

If you want to translate things, a guide is here: https://github.com/BigWigsMods/BigWigs/wiki/Translating-a-Locale
Just do the same but for LittleWigs instead of BigWigs.
