### ISSUE TITLE
DeOtherSide/Hakkar: Missing Piercing Barb

### ISSUE THREAD

**Issue by Sollantos** [BigWigsMods/LittleWigs#544]
Hi there, 

I wanted to go back to Bigwigs/Littlewigs, but it seems like certain dungeon boss mechanics are missing. In specific I'm missing Piercing Barb on Hakkar the Soulflayer in De Other Side. Is it possible that some mechanics are missing and can they be added? As tank those type of abilities are the most important to keep track of.

Thanks in advance.

**Comment by Justw8** [comment]
Yes, we plan to update and fix it all up in due time, please list anything specific you feel like is missing in addition to Piercing Barb.

**Comment by funkydude** [comment]
Closed by commit 0dbebb378c8bb2ba0972aaba61d5e4e12fa8bd78 for next release.
