### ISSUE TITLE
The Necrotic Wake/Trash - auto marking 

### ISSUE THREAD

**Issue by acidrain313** [BigWigsMods/LittleWigs#545]
Hello. I'm korean wow player, so my english skills may be a little insufficient.

When I go to mythic or mythic+ necrotic wake, trash name "Zolamus Necromancer"(id:163618) is always been auto marked with skull when trash is on my sight. Some trash in theater of pain also auto marking. I'm in this situation since shadowland's first week. This situation makes uncomfortable situation when I'm doing mythic+ run with my team. I check my weakauras so many times, but I'm not using auto-marking weakauras.

All I just want to know is this. Does littlewigs offering this automarking function? If not, I will find solution in my another addons. But I think my other addons have no reason to offering dungeon automarking function.

**Comment by Zireael-N** [comment]
LittleWigs does not mark these mobs. We did not even have a module for trash from The Necrotic Wake until yesterday.

**Comment by acidrain313** [comment]
> LittleWigs does not mark these mobs. We did not even have a module for trash from The Necrotic Wake until yesterday.

Thanks for quick reply.

**Comment by Justw8** [comment]
If you want to know what does: Plater Nameplates afaik
