### ISSUE TITLE
Sanguine Depths, Executor Tarvold: Coalesce Manifestation

### ISSUE THREAD

**Issue by redcatelf** [BigWigsMods/LittleWigs#555]
In Sanguine Depths, Executor Tarvold, I don't see any bars or sound showing for Coalesce Manifestation, the add summon ability, even though I have bars and sound [activated](https://user-images.githubusercontent.com/44137029/103488583-b2699900-4e05-11eb-9a6a-922bcd7e2ab1.png). Only the Castigate bar shows up.

According to my combat timer, it seems that the boss summons the [Fleeting Manifestation](https://www.wowhead.com/npc=168882/fleeting-manifestation) at about 13 seconds into the fight, and then every 30 seconds.

Note that while I do find the Coalesce Manifestation spell on Wowhead at [322573](https://www.wowhead.com/spell=322573/coalesce-manifestation) and [322574](https://www.wowhead.com/spell=322574/coalesce-manifestation), it doesn't ever show in my log's [list of casts](https://www.warcraftlogs.com/reports/1yBAkmRza6vqwM2h#fight=3&type=casts&hostility=1&by=ability). The Fleeting Manifestation seems to just appear out of thin air. Therefore perhaps Littlewigs shouldn't try watching for a Coalesce Manifestation cast in the combat log.

**Comment by Zireael-N** [comment]
Fixed in 7760df955.

> Note that while I do find the Coalesce Manifestation spell on Wowhead at 322573 and 322574, it doesn't ever show in my log's list of casts. 

UNIT_SPELLCAST_SUCCEEDED events are not included in combat logs. You can record them using Transcriptor though.

**Comment by redcatelf** [comment]
Thank you!
