### ISSUE TITLE
Icebound Aegis not reporting

### ISSUE THREAD

**Issue by redcatelf** [BigWigsMods/LittleWigs#556]
For boss Nalthor in The Necrotic Wake on mythic keystone difficulty, Icebound Aegis doesn't make any sound.

I see that in the source it's configured to listen for [321368](https://www.wowhead.com/spell=321368/icebound-aegis), but I believe that's the normal/heroic version of the spell. The mythic version is [321754](https://www.wowhead.com/spell=321754/icebound-aegis).

**Comment by funkydude** [comment]
Fixed in the latest release, thanks!
