### ISSUE TITLE
 Spires of Ascension: Oryphrion timers

### ISSUE THREAD

**Issue by redcatelf** [BigWigsMods/LittleWigs#559]
I have a few suggestions for Oryphrion in Spires of Ascension:

* As the Recharge Anima cast begins, we should cancel the timers on Purifying Blast, Empyreal Ordnance, and Charged Stomp. See [this screenshot](https://user-images.githubusercontent.com/44137029/103680371-ff707b00-4f7d-11eb-9a16-f800946a4efc.jpg).
* When Recharge Anima finishes, the boss seems to resume their original rotation, so we could reset all of the timers. Right now they seem to have some issues resyncing.
* The Drained bar in the screenshot could perhaps be named Cast: Recharge Anima to make it more obvious.
* The Drained bar seems to be a fixed timer, but the Recharge cast can end sooner if some orbs get to the boss.
* It could be worth adding a timer for the Empyreal Ordnance cast progression (3.0 sec), since at the end of the cast your position gets locked in and you need to start moving out.
* After the Empyreal Ordnance cast ends, we could even consider having another timer until the patches explode. It looks like it's exactly 3.0 seconds in my recording.
* Is it worth adding cast timers for Charged Stomp and Purifying Blast, or is that overkill? Both abilities deal their damage at the end of the cast.
* Sometimes the timers end up putting the abilities too close. For example, I got the following bars:

    ![image](https://user-images.githubusercontent.com/44137029/103682495-df8e8680-4f80-11eb-9c12-a78e38f846a5.png)

    In my recording, the Purifying Blast did start roughly on time, but the time between the cast starts of Purifying Blast and Empyreal Ordnance was 4.9 seconds, since Purifying Blast takes 2.5 seconds to cast and there's presumably some minimum idle time between casting two abilities. (The boss melee'd the tank once in between.)

Is this kind of detail in a bug report useful at all? I could also upload a screen recording (of this boss fight, or other fights in the future) if that helps.

**Comment by Zireael-N** [comment]
Thanks for your feedback. This module needs to be revisited, it's very basic at the moment.

> The Drained bar in the screenshot could perhaps be named Cast: Recharge Anima to make it more obvious.

This bar shows time left until the next Drained application, not its duration.

>  Recharge cast can end sooner if some orbs get to the boss.

Same with Drained being applied, it could be delayed if the boss casts something while standing in [Anima Field](https://www.wowhead.com/spell=324392/anima-field).

> I could also upload a screen recording (of this boss fight, or other fights in the future) if that helps.

If you could upload logs produced by [Transcriptor](https://www.curseforge.com/wow/addons/transcriptor), that would be immensely helpful (`/ts` to start/end logging, `/ts clear` to clear existing logs, logs will be written to `WTF\account\SavedVariables\Transcriptor.lua` on logout). Preferably, with at least one clean Recharge Anima phase and at least one where an orb reaches the boss.
