### ISSUE TITLE
Sound alerts doesn't work on Tred'ova's parasitic* casts

### ISSUE THREAD

**Issue by mbelsky** [BigWigsMods/LittleWigs#564]
Hey,

Thank you for this awesome addon!

There are three most important casts on Tred'ova boss:

- https://www.wowdb.com/spells/337255-parasitic-domination
- https://www.wowdb.com/spells/337251-parasitic-incapacitation
- https://www.wowdb.com/spells/337235-parasitic-pacification

And it looks like you have added sound alerts for them: https://github.com/BigWigsMods/LittleWigs/blob/master/Shadowlands/MistsOfTirnaScithe/Options/Sounds.lua#L24

However as you may hear this sound alarms don't play, just text notifications:

- https://youtu.be/KKA6I7ap3Ew?t=1557
- https://youtu.be/KKA6I7ap3Ew?t=1590
- https://youtu.be/KKA6I7ap3Ew?t=1633
- https://youtu.be/KKA6I7ap3Ew?t=1658

Is that behavior expected?

**Comment by Justw8** [comment]
At the moment it only plays a sound when you are targeted, I believe this was due to it not being interruptedable on beta.

It should be changed to play a sound when you have kick ready, thanks for reporting it.
