### ISSUE TITLE
Failing In Torghast

### ISSUE THREAD

**Issue by tflo** [BigWigsMods/LittleWigs#565]
Seems that have-to-interrupt spells are not announced in Torghast at all.

Not sure if this is a bug, or if the add-on is simply not yet updated to Shadowlands, but I think that once I _did_ get a warning, but currently I have to use DBM. So, not sure.

**Comment by funkydude** [comment]
BigWigs is for raids, moving issue to LittleWigs project.

**Comment by tflo** [comment]
Ah, sure, sorry. Thanks for moving.

**Comment by tflo** [comment]
PS:

Take the “but I think that once I did get a warning” from my OP as anecdotal, because – in hindsight – it could also be that it was a warning from a TMW script I had set up at that time. (Shortly after, I switched to DBM, so unverified.)

**Comment by N6REJ** [comment]
I can confirm that little wigs is NOT working in torghast

**Comment by funkydude** [comment]
It's unlikely timers for this will be added at this stage. There was never any real major indicator from players that these were necessary,
