### ISSUE TITLE
Spires of Ascension/Kin-Tara

### ISSUE THREAD

**Issue by Deorigosa** [BigWigsMods/LittleWigs#567]
Whenever the boss changes phases, the *first* [Charged Spear](https://www.wowhead.com/spell=321009/charged-spear) on the phase is detected badly.

The addon consistently announces the spear target to be the boss target, not the spear cast target.

Consistently reproducible on all difficulties

**Comment by Justw8** [comment]
There was an update for this 7 hours ago with https://github.com/BigWigsMods/LittleWigs/commit/14931016ed433b7124fe5a1c29e8bea06f2fd55d

Could you please try those out and let us know if this still happens?

**Comment by Deorigosa** [comment]
I will definitely do that.

The change is not reflected in the patch notes, so I thought it wasn't fixed yet

**Comment by Justw8** [comment]
Maybe your updater did not have it available yet, as it was only in the alpha.

**Comment by Deorigosa** [comment]
It actually works now! Good to know
