### ISSUE TITLE
Missing ability in Halls of Atonement trash

### ISSUE THREAD

**Issue by okazan** [BigWigsMods/LittleWigs#574]
Powerful Swipe casted by the Stoneborn Slashers is missing

It's an important fixed frontal cone just like the Deadly Thrust off of Depraved Darkblades from the same dungeon. Deadly thrust is tracked by the addon whereas Powerful Swipe is not.

**Comment by Zireael-N** [comment]
Fixed in 3ca703ce9ec0d8f39fe69807363ce56b1f7ce2d4.
