### ISSUE TITLE
Error in CoT: Durnholde

### ISSUE THREAD

**Issue by houlia** [BigWigsMods/LittleWigs#599]
## Describe the problem
Getting the Following constantly in Cot: Durnholde.  Being in the instance (after dragon flies you)

98x ...igs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:53: attempt to index global 'C_Scenario' (a nil value)
[string "@LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua"]:53: in function `VerifyEnable'
[string "@BigWigs_Core\Core.lua"]:127: in function <BigWigs_Core\Core.lua:124>
[string "@BigWigs_Core\Core.lua"]:138: in function <BigWigs_Core\Core.lua:132>
[string "@BigWigs_Core\Core.lua"]:154: in function <BigWigs_Core\Core.lua:143>
[string "@BigWigs_Core\Core.lua"]:160: in function `v'
[string "@BigWigs_Core\Core.lua"]:57: in function <BigWigs_Core\Core.lua:54>

Locals:
self = <table> {
 instanceId = 560
 RegisterMessage = <function> defined @BigWigs\Loader.lua:832
 UnregisterMessage = <function> defined @BigWigs\Loader.lua:853
 colorOptions = <table> {
 }
 VerifyEnable = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:49
 soundOptions = <table> {
 }
 HammerOfJusticeRemoved = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:85
 Consecration = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:70
 SendMessage = <function> defined @BigWigs\Loader.lua:867
 SetupOptions = <function> defined @BigWigs_Core\Core.lua:638
 Interrupt = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:94
 OnBossEnable = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:38
 journalId = 539
 RegisterEvent = <function> defined @BigWigs_Core\Core.lua:64
 HolyLight = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:89
 HammerOfJustice = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:78
 displayName = "Captain Skarloc"
 enableMobs = <table> {
 }
 engageId = 1907
 name = "BigWigs_Bosses_Captain Skarloc"
 GetOptions = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:29
 localization = <table> {
 }
 moduleName = "Captain Skarloc"
 UnregisterEvent = <function> defined @BigWigs_Core\Core.lua:71
 CHAT_MSG_MONSTER_SAY = <function> defined @LittleWigs_BurningCrusade\OldHillsbradFoothills\Skarloc.lua:61
}
_ = "party4target"
mobId = 17833
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_Scenario' (a nil value)"

### What steps will reproduce the problem?

1.  take dragon path to start
2.  get in combat
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
9.0.34

### Do you have an error log of what happened?
above

**Comment by nebularg** [comment]
You need to use the classic version of LittleWigs with BCC, the latest version is v4-classic-bcc

**Comment by houlia** [comment]
addon manager (ajour) grabbed the wowinterface version somehow - in case anyone else has a similar problem in the future

**Comment by funkydude** [comment]
WoWI has all the correct versions available regardless. We recommend the [CurseForge app](https://curseforge.overwolf.com/) to avoid such 3rd party tool issues.
