### ISSUE TITLE
Support CoS spy event

### ISSUE THREAD

**Issue by stsundermann** [BigWigsMods/LittleWigs#6]
The recent alpha in DBM has brought initial support for the CoS spy event. The hints from the NPCs are parsed and displayed for all DBM users in a info frame. It'd be cool if little wigs had a similar feature.

**Comment by oleerik** [comment]
Absolutely agree!

**Comment by oleerik** [comment]
I've been looking a bit into it but I'm not quite sure how this would be done. Is there a way of triggering the infobox based on where you are, rather than what boss you are fighting?

**Comment by Gnarfoz** [comment]
I think that's usually done by way of creating a "Trash" boss module and enabling/disabling it based on relevant NPCs.
Cf. https://github.com/BigWigsMods/BigWigs/blob/master/Nightmare/Trash.lua

**Comment by oleerik** [comment]
Ah, interesting. Thank you very much @Gnarfoz!

**Comment by Gnarfoz** [comment]
Doesn't look like it cares:

https://github.com/BigWigsMods/BigWigs/wiki/BossPrototype#registerenablemob-
https://github.com/BigWigsMods/BigWigs/blob/master/Core/Core.lua#L134

**Comment by elvador** [comment]
Long time overdue, but finally added in d61f481.
