### ISSUE TITLE
Best time bar not showing up in TBC version

### ISSUE THREAD

**Issue by Nahoda** [BigWigsMods/LittleWigs#601]
As title says, in settings i have checked best time bar but  it's not showing up. Is that feature only for raids ? Thanks for clarifying

**Comment by Justw8** [comment]
I do believe this is currently a raid only feature.

**Comment by funkydude** [comment]
Can you please explain why you think a best time for dungeon bosses is useful?

**Comment by Nahoda** [comment]
No specific reason, just a information. DBM has it working even for dungeons thought BigWigs / LittleWigs would have it too. Like you said its not a really useful feature, if it was there, i would use it. I was just asking

**Comment by funkydude** [comment]
Thanks for explaining @Nahoda I'm just looking to see if people would find this genuinely useful.
