### ISSUE TITLE
Little Wigs: Black Morass

### ISSUE THREAD

**Issue by Rentaur** [BigWigsMods/LittleWigs#603]
## Describe the problem
Timers depicting each temporal gateway are not accurate.

### What steps will reproduce the problem?

1.  Opening the Dark Portal: Black Morass in the caverns of time, rift/wave timers are not accurate
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v5-classic (2021-06-06)

**Comment by funkydude** [comment]
In what way are they not accurate? Please be specific.

**Comment by ikt** [comment]
The timers are way off.

I don't think the timer bar is even on my screen counting down between breaks it's so far off.

edit: Also appreciate all the work you've done over the years.

**Comment by nebularg** [comment]
Timer after boss death should be good now

**Comment by funkydude** [comment]
Fixed in the next v6-classic release, thanks for reporting this!
