### ISSUE TITLE
Auchenai Crypts - Exarch Maladaar

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/LittleWigs#604]
## Describe the problem
Error happens during the encounter and the success message plays when the boss dies but he spawns an avatar when his hp is near 15% so the encounter is not over.

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v6

### Do you have an error log of what happened?
2x BigWigs_Core\BossPrototype.lua:180: attempt to compare number with string
[string "@BigWigs_Core\BossPrototype.lua"]:180: in function <BigWigs_Core\BossPrototype.lua:178>
[string "@BigWigs_Core\BossPrototype.lua"]:1231: in function `SpellName'
[string "@LittleWigs\TBC\AuchenaiCrypts\Maladaar.lua"]:59: in function `?'
[string "@BigWigs_Core\Core.lua"]:59: in function <BigWigs_Core\Core.lua:54>

Locals:
self = <table> {
}
key = "Avatar of the Martyred"
value = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with string"
GetSpellInfo = <function> defined =[C]:-1
core = <table> {
 AddColors = <function> defined @BigWigs_Core\Core.lua:700
 RegisterEnableMob = <function> defined @BigWigs_Core\Core.lua:163
 Enable = <function> defined @BigWigs_Core\Core.lua:379
 NewBoss = <function> defined @BigWigs_Core\Core.lua:445
 CancelTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:147
 GetRoleOptions = <function> defined @BigWigs_Core\Constants.lua:91
 RegisterBossModule = <function> defined @BigWigs_Core\Core.lua:650
 GetPlugin = <function> defined @BigWigs_Core\Core.lua:533
 TimeLeft = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:172
 GetEnableMobs = <function> defined @BigWigs_Core\Core.lua:186
 ScheduleRepeatingTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:160
 NewBossLocale = <function> defined @BigWigs_Core\Core.lua:429
 AddSounds = <function> defined @BigWigs_Core\Core.lua:709
 GetOptions = <function> defined @BigWigs_Core\Constants.lua:87
 name = "BigWigs"
 IsEnabled = <function> defined @BigWigs_Core\Core.lua:409
 ScheduleTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:94
 C = <table> {
 }
 Print = <function> defined @BigWigs_Core\Core.lua:413
 RegisterOption = <function> defined @BigWigs_Core\Constants.lua:33
 db = <table> {
 }
 SendMessage = <function> defined @BigWigs\Loader.lua:934
 IterateBossModules = <function> defined @BigWigs_Core\Core.lua:517
 RegisterEvent = <function> defined @BigWigs_Core\Core.lua:64
 IteratePlugins = <function> defined @BigWigs_Core\Core.lua:529
 GetBossOptionDetails = <function> defined @BigWigs_Core\Constants.lua:154
 GetOptionDetails = <function> defined @BigWigs_Core\Constants.lua:83
 RegisterPlugin = <function> defined @BigWigs_Core\Core.lua:677
 GetBossModule = <function> defined @BigWigs_Core\Core.lua:521
 Test = <function> defined @BigWigs_Core\Core.lua:227
 NewPlugin = <function> defined @BigWigs_Core\Core.lua:492
 UnregisterEvent = <function> defined @BigWigs_Core\Core.lua:71
 Error = <function> defined @BigWigs_Core\Core.lua:417
}
format = <function> defined =[C]:-1
C_EncounterJournal_GetSectionInfo = <function> defined @BigWigs_Core\BossPrototype.lua:30

**Comment by funkydude** [comment]
Thanks, this is now fixed.
In regards to the "success message" playing, I don't plan on changing this.
The encounter is considered over when you kill him. You can loot him despite being in combat, and if you wipe on the add you can just run back and loot the boss still.
If Blizz changes the encounter then we can adapt the boss module.
