### ISSUE TITLE
Wrong timer on Murmur debuff

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/LittleWigs#605]
## Describe the problem
The timer for Murmur's Touch is too short, when it expired I think I still had about 6 seconds left on the debuff.
This was on normal mode.

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v7

**Comment by funkydude** [comment]
Turns out this is actually an issue in BigWigs, will be fixed in the next BigWigs bcc release, thanks for reporting.
