### ISSUE TITLE
Theater of Pain - First Boss - Xira the Underhanded

### ISSUE THREAD

**Issue by BigBont** [BigWigsMods/LittleWigs#607]
On Russian client in journal - Xira the Underhanded - have no Rus name - Зира Двурушница
and BigWigs send error message in the chat.

![image](https://user-images.githubusercontent.com/16833/124283426-ccc9c880-db43-11eb-893c-cb5e525ce567.png)

**Comment by funkydude** [comment]
Not a BigWigs issue - moving to LittleWigs.
