### ISSUE TITLE
Halls of Atonement

### ISSUE THREAD

**Issue by s2kallday** [BigWigsMods/LittleWigs#608]
There appears to be a large discrepancy in the Sinlight Visions timer and the start of the cast. I'd say close to 7-10secs worth.

Cheers.

**Comment by nebularg** [comment]
See https://github.com/BigWigsMods/LittleWigs/issues/587#issuecomment-787098725. Sinlight Visions is just one of those abilities that can be off randomly because the boss can use Heave and/or Slam before the cast after hitting 100 energy.
