### ISSUE TITLE
Hardly any timers for TBC Dungeons

### ISSUE THREAD

**Issue by hardtofin** [BigWigsMods/LittleWigs#611]
In TBC, hardly any bosses in any of the dungeons have timers or bars is this as expected?  I am unsure if there is some bug or there are only a few timers.

### What steps will reproduce the problem?

This can be reproduced by playing any TBC dungeon

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v7 classic bcc

### Do you have an error log of what happened?
No, there is no error log produced

**Comment by funkydude** [comment]
It's unlikely this will change now that BCC is ending.
