### ISSUE TITLE
Add back Mage Tower for 9.1.5 Legion Timewalking

### ISSUE THREAD

**Issue by gareth3001** [BigWigsMods/LittleWigs#617]
## Describe the problem

The Mage Tower timers appear to have been deleted after 8.0, but 9.1.5 adds them back as part of Legion Timewalking.

### What steps will reproduce the problem?

1.  Enter Mage Tower in 9.1.5, no timers.

### What version of LittleWigs are you using? (Stating 'latest' is not useful)

9.1.4

**Comment by nebularg** [comment]
Added in a13a85c35fa9890a13260db19fb35498a566504a
