### ISSUE TITLE
Unknown Spell found in Healer Mage Tower

### ISSUE THREAD

**Issue by LiangYuxuan** [BigWigsMods/LittleWigs#625]
## Describe the problem
Unknown Spell found in Healer Mage Tower

### What steps will reproduce the problem?

1.  Enter healer mage tower challenge and get this in Stage 1

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v9.1.5

### Do you have an error log of what happened?
```
1x Found spell '奥术突袭' using id 235833 on 24, tell the authors!
[string "@BigWigs_Core\BossPrototype.lua"]:1243: in function `UnitBuff'
[string "@LittleWigs_Legion\ArtifactScenarios\LordErdrisThorn.lua"]:115: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:541: in function <BigWigs_Core\BossPrototype.lua:507>
```

### Any additional information? (example: WoW language if not English)
It's a buff on caster mobs. A warning for stacks would be perfect.

**Comment by nebularg** [comment]
Looks like it should be warning on 3 stacks.  The error is because it's using the spell name for the buff scan instead of the id, but it should still work.
