### ISSUE TITLE
Theater of Pain trash abilities

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/LittleWigs#638]
## Describe the problem

Notable abilities of trash in Theater of Pain that LittleWigs should be tracking but isn't, listed by mob that casts them:

- [Soulforged Bonereaver](https://www.wowhead.com/npc=162763/soulforged-bonereaver):
    - [Bone Spikes](https://www.wowhead.com/spell=331237/bone-spikes), avoid stuff on the ground
    - [Bonestorm](https://www.wowhead.com/spell=331223/bonestorm), avoid it
- [Manical Soulbinder](https://www.wowhead.com/npc=160495/maniacal-soulbinder):
    - [Soul Corruption](https://www.wowhead.com/spell=333708/soul-corruption), dispellable debuff on players (magic)
- [Nefarious Darkspeaker](https://www.wowhead.com/npc=169893/nefarious-darkspeaker):
    - [Curse of Desolation](https://www.wowhead.com/spell=333299/curse-of-desolation), dispellable debuff on players (curse), or let the player dodge the ground effect it spawns
- [Portal Guardian](https://www.wowhead.com/npc=167998/portal-guardian):
    - [Shadow Vulnerability](https://www.wowhead.com/spell=330725/shadow-vulnerability), dispellable debuff on players (curse)
    - [Soulstorm](https://www.wowhead.com/spell=330716/soulstorm), high damage
- [Blighted Sludge-Spewer](https://www.wowhead.com/npc=174210/blighted-sludge-spewer):
    - [Withering Blight](https://www.wowhead.com/spell=341949/withering-blight), dispellable debuff on players (disease)
- [Diseased Horror](https://www.wowhead.com/npc=170690/diseased-horror):
    - [Decaying Blight](https://www.wowhead.com/spell=330700/decaying-blight), dispellable debuff on players (disease)
    - [Meat Shield](https://www.wowhead.com/spell=341977/meat-shield), stunnable shield on the mob
- [Dokigg the Brutalizer](https://www.wowhead.com/npc=167538/dokigg-the-brutalizer):
    - [Battle Trance](https://www.wowhead.com/spell=342139/battle-trance), dispellable/interruptable buff on the mob
    - [Brutal Leap](https://www.wowhead.com/spell=342125/brutal-leap), jumps on a random player location
- [Heavin the Breaker](https://www.wowhead.com/npc=167532/heavin-the-breaker):
    - [Battle Trance](https://www.wowhead.com/spell=342139/battle-trance), dispellable/interruptable buff on the mob
    - [Ricocheting Blade](https://www.wowhead.com/spell=333861/ricocheting-blade), targets a random player and debuffs them (players should spread)
- [Advent Nevermore](https://www.wowhead.com/npc=167533/advent-nevermore):
    - [Ricocheting Blade](https://www.wowhead.com/spell=333861/ricocheting-blade), targets a random player and debuffs them (players should spread)
- [Harugia the Bloodthirsty](https://www.wowhead.com/npc=167536/harugia-the-bloodthirsty):
    - [Battle Trance](https://www.wowhead.com/spell=342139/battle-trance), dispellable/interruptable buff on the mob
    - [Ricocheting Blade](https://www.wowhead.com/spell=333861/ricocheting-blade), targets a random player and debuffs them (players should spread)
- [Nekthara the Mangler](https://www.wowhead.com/npc=162744/nekthara-the-mangler):
    - [Whirling Blade](https://www.wowhead.com/spell=336996/whirling-blade), targets a random player location
    - [Whirlwind](https://www.wowhead.com/spell=317605/whirlwind), players should avoid
    - [Interrupting Roar](https://www.wowhead.com/spell=342135/interrupting-roar), casters should stop casting
- [Shambling Arbalest](https://www.wowhead.com/npc=164510/shambling-arbalest):
    - [Jagged Quarrel](https://www.wowhead.com/spell=330532/jagged-quarrel), debuff inflicting large amounts of damage to a player
- [Unyielding Contender](https://www.wowhead.com/npc=170838/unyielding-contender):
    - [Death Wish](https://www.wowhead.com/spell=331510/death-wish), buff on mob that can be tranqulized
- [Raging Bloodhorn](https://www.wowhead.com/npc=170850/raging-bloodhorn):
    - [Raging Tantrum](https://www.wowhead.com/spell=333241/raging-tantrum), buff on mob that should be tranquilized

There are probably some I missed, but this should cover most of what LittleWigs is currently missing.

### What version of LittleWigs are you using? (Stating 'latest' is not useful)

9.2.2

**Comment by ntowle** [comment]
> [Decaying Blight](https://www.wowhead.com/spell=330700/decaying-blight), dispellable debuff on players (disease)
> [Jagged Quarrel](https://www.wowhead.com/spell=330532/jagged-quarrel), debuff inflicting large amounts of damage to a player

I'm not sure these should be tracked because they would both be very spammy.

Decaying Blight can stack in ~3.5 seconds and just a few stacks are not dangerous. Maybe a high stack alert would be good?

Not much you can do about Jagged Quarrel anyway, plus two Arbalests can cast it 24 times in 1 minute.

> [Death Wish](https://www.wowhead.com/spell=331510/death-wish), buff on mob that can be tranqulized

I'm not sure this should be tracked as it's a low priority to soothe this and may even be detrimental as it also makes the mob take more damage.
