### ISSUE TITLE
Error Message in Necrotic Wake

### ISSUE THREAD

**Issue by DiscordGregory** [BigWigsMods/LittleWigs#741]
### What steps will reproduce the problem?
Didn't do anything out of the ordinary, was in fight with first boss of Necrotic Wake in normal mode.

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
9.2.16

### Do you have an error log of what happened?
2x ...ittleWigs\Shadowlands\TheNecroticWake\Blightbone.lua:60: attempt to call method 'StackMessageOld' (a nil value)
[string "@LittleWigs\Shadowlands\TheNecroticWake\Blightbone.lua"]:60: in function `?'
[string "@BigWigs_Core\BossPrototype.lua"]:529: in function <BigWigs_Core\BossPrototype.lua:495>

Locals:
Skipped (In Encounter)

**Comment by ntowle** [comment]
Update your BigWigs, the current version is v246.3.

**Comment by DiscordGregory** [comment]
I see, for some reason the curse client says that the addon (among others) was "Modified" and it wasn't indicating there was an update. Right clicking and choosing "Update" downloaded the current version.

**Comment by funkydude** [comment]
> I see, for some reason the curse client says that the addon (among others) was "Modified" and it wasn't indicating there was an update. Right clicking and choosing "Update" downloaded the current version.

When was the last time you restarted the app? Do you keep it open for long periods of time (days/weeks) ?
