### ISSUE TITLE
Why addon skip dialogue choices by default in dungeons?

### ISSUE THREAD

**Issue by SegoItCh** [BigWigsMods/LittleWigs#790]
1.  The Culling of Stratholme
2.  Talk to Chromie 
3.  Yoinked right to the Arthas

9.2.25

**Comment by ntowle** [comment]
You can uncheck the "Autotalk" option under Wrath of the Lich King -> The Culling of Stratholme Trash module to disable the feature.

**Comment by SegoItCh** [comment]
But why it's on by default? It breaks immersion and RP

**Comment by Justw8** [comment]
If you want immersion, don't use addons. It's on by default as installing the addon is the 'enable' button, you can config it after if you want to personalize it.
