### ISSUE TITLE
Karazhan

### ISSUE THREAD

**Issue by epodox** [BigWigsMods/LittleWigs#8]
Is there anyway to get support for the Karazhan bosses?

**Comment by jkw** [comment]
They're working on them. A few have been added, but not all. Logs are needed to determine timers etc.

**Comment by mkarer** [comment]
I created a Magic Magnificent timer/alert for Wikket because the one from Blizzard is shown way too late:
http://pastebin.com/H2aLKsXx

**Comment by funkydude** [comment]
@mkarer I suggest you create a pull request.

**Comment by elvador** [comment]
Done, they'll need some more work though. Please report anything wrong/missing.
