### ISSUE TITLE
Auto dialog selects incorrect option in Trial of the Champion

### ISSUE THREAD

**Issue by Rynocat** [BigWigsMods/LittleWigs#814]
## Describe the problem
Ever since 10.0 prepatch, Littlewigs auto dialog selects the option that doesn't skip the rp (option 2 in image below) rather than the option to skip rp (option 1).

### What steps will reproduce the problem?

1.  Talk to Arelas Brightstar in Trial of the Crusader dungeon
2.  
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/81334765/199179578-665e1a50-5d66-43dd-aa94-c5e823007071.png)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
10.0.3

### Do you have an error log of what happened?
N/A

**Comment by funkydude** [comment]
Thanks for reporting this!
