### ISSUE TITLE
Halls of Infusion Trash names changed

### ISSUE THREAD

**Issue by Dynaletik** [BigWigsMods/LittleWigs#834]
Hey,

when translating, I just saw that 2 of the trash mob dragons in Halls of Infusion have gotten slightly different names on Live:

Oceanic Proto-Dragon -> Glacial Proto-Dragon (https://www.wowhead.com/npc=190403/glacial-proto-dragon)
Earthen Proto-Dragon -> Subterranean Proto-Dragon (https://www.wowhead.com/npc=190404/subterranean-proto-dragon)

For deDE, the names are already correctly translated.

Kind regards,
Dyna

**Comment by ntowle** [comment]
Thanks!
