### ISSUE TITLE
DF : Mobs missing in dongeon settings

### ISSUE THREAD

**Issue by Namsty** [BigWigsMods/LittleWigs#840]
I just saw that some trash are missing in the "trash" section of the Nokhud dongeon.

Do you intend to add the missing ones or not ?

I haven't looked for the other dungeons yet.

**Comment by ntowle** [comment]
Only trash with important abilities are added. For Nokhud there are a few more which will be added soon:

Primalist Stormspeaker's Tempest
Primalist Stormspeaker's Summon Squall

Primalist Thunderbeast's Thunderstrike
Primalist Thunderbeast's Thunder Clap

Ukhel Deathspeaker's Chant of the Dead

Ukhel Beastcaller's Desecrating Roar

**Comment by ntowle** [comment]
Fixed by 2ccaf1b.
