### ISSUE TITLE
Missing dungeon spells

### ISSUE THREAD

**Issue by 4ydan** [BigWigsMods/LittleWigs#845]
## Describe the problem

I would like to make a list of missing abilities for the new set of M+ dungeons.
Maybe it helps you, if not just ignore this.
I will update this list over time and remove stuff you have added.

### What steps will reproduce the problem?

1.  /bw
2.  Cant find the spells at boss or trash section

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
![image](https://user-images.githubusercontent.com/53004139/208299561-b9dc4554-f805-41a2-9d85-46872263f9d5.png)

## The Azure Vault

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
|  [Drakonid Breaker](https://www.wowhead.com/npc=187240/drakonid-breaker)  |  Bestial Roar  |  396991 | AOE | 

## Ruby Life Pools

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
|  [Flashfrost Earthshaper](https://www.wowhead.com/npc=187969/flashfrost-earthshaper) |  Tectonic Slam | 372735 |  AOE INTERRUPTABLE  | 

## Court of Stars

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
|  Shadow Mistress  |  Shadow Slash |  211473 |TANK_HEALER | 

## Shadowmoon Burial Grounds

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
|  Bonemaw  |  Corpse Breath |  165579 | AOE HEALER_WARNING |

## Temple of the Jade Serpent

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
| Corrupt Living Water  |  Tainted Ripple | 397878 |  AOE| 
|  [Haunting Sha](https://www.wowhead.com/npc=58856/haunting-sha)  |  Haunting Gaze |  114646 | TANK_HEALER   |
|  Fallen Waterspeaker  |  Tidal Burst |  | Description missing |

## Nokhud Offensive

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
| Nokhud Hornsounder |  Rally the Clan | 383823| ENEMY_BUFF | 
| Primalist Stormspeaker  |  Tempest | 386024 or 386025 | AOE INTERRUPTABLE  | 

## Algathar Academy

|  NPCName  |  Spell  |  SpellId | Info  |  
|---|---|---|---|
| Alpha Eagle  | Gust | 377383 |  FRONTAL | 
| Guardian Sentry  | Storm Slash | 377991|  TANK_HEALER | 

>

**Comment by ntowle** [comment]
> Nokhud Beastmaster	Summon War Ohuna	383690

Abilities you cannot do anything about (especially instant cast abilities) will not be added as that just creates noise.

> Melidrussa Chillworn	Frigid Shard
> Reanimated Ritual Bones	Void Slash	164907
> Nokhud Warspear	Pierce	384134
> Primal Juggernaut	Crushing Smash	372730
> Minion of Doubt	Dark Claw	397931

Mobs that spam some uninterruptible ability to hit the tank where that ability doesn't do anything special will not be added for the same reason.

> Wise Mari	Hydrolance
> Stormcaller Arynga	Stormbolt	386012

Spammable yet interruptible tank-hits have to be genuinely dangerous to be added, these are still under evaluation as keys get pushed higher but for now I'd rather err on the side of avoiding alert-fatigue.

> Primalist Stormspeaker	Tempest	386024 or 386025
> Monstrous Corpse Spider	Necrotic Burst	156718

Added.

> Drakonid Breaker	Bestial Roar	396991
> Alpha Eagle	Gust	377383
> Corrupt Living Water	Tainted RIpple	397878

On the todo list.

**Comment by 4ydan** [comment]
Alright, thanks for the clarificatio, I will update the list.
Just want to point out that Reanimated Ritual Bones Void Slash 164907 can one shot the tank on higher fortified keys, so this has to be outranged or stopped.

**Comment by ntowle** [comment]
Fixed by:

https://github.com/BigWigsMods/LittleWigs/commit/6f6e0cd0156a06d7f8e8e80be985ad628c9d0907
https://github.com/BigWigsMods/LittleWigs/commit/2d323694aff559a1f5ba1fbc22b8d071ee98e88d
https://github.com/BigWigsMods/LittleWigs/commit/01e14ad903632781f10416cf25b2d6862968ac00
https://github.com/BigWigsMods/LittleWigs/commit/2f517ba126e15b4304d6c0fe10e71abb96a94638
and others.
