### ISSUE TITLE
Nhallish Void Blast Shadowmoon Burial Grounds missing

### ISSUE THREAD

**Issue by 4ydan** [BigWigsMods/LittleWigs#849]
## Describe the problem

Frontal Void Blast Ability missing on this boss in Shadowmoon Burial Grounds

![image](https://user-images.githubusercontent.com/53004139/209417917-97eded88-778a-422a-a7f0-87975332f5d7.png)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)

![image](https://user-images.githubusercontent.com/53004139/209417941-b743b2f7-165c-407a-9a63-c6651cd92764.png)

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/2885ac7bed613847a4d2a15f25a9aae8b8e2552f.
