### ISSUE TITLE
Court of Stars - Announce in party chat the found items, Not just only for me.

### ISSUE THREAD

**Issue by WybeBosch** [BigWigsMods/LittleWigs#850]
## Describe the problem
Right now if you are in court of stars dungeon, if you hover over special items that will give you a buff or spawn a miniboss it will show up in your "messages" of bigwigs. (Very nice). However i would like the option to somehow output this to chat once i find one of these items. 

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://user-images.githubusercontent.com/40889930/209447018-cf66a066-bb5c-4cd6-8219-b35cfc91f96f.png)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
[v10.0.17](https://github.com/BigWigsMods/LittleWigs/tree/v10.0.17) (2022-12-21)

**Comment by funkydude** [comment]
This likely won't change, sorry
