### ISSUE TITLE
Missing dispellable magic debuff in Shadowmoon Burial Grounds

### ISSUE THREAD

**Issue by steven-joruk** [BigWigsMods/LittleWigs#857]
Can you add this spell please?

Shadowmoon Bone-Mender (75713) casts Shadow Word: Frailty (152819). It's a magic debuff that should be dispelled.

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/35c0a321dd9ac6a814944db99d7486ac230489c9.
