### ISSUE TITLE
ER: Add spell timers for Shadowmoon Burial Grounds boss fights

### ISSUE THREAD

**Issue by jury** [BigWigsMods/LittleWigs#858]
Shadowmoon Burial Grounds does not have any timers implemented for the boss fights, which makes it difficult for this season of M+. It would be great to get those implemented.

**Comment by ntowle** [comment]
Timers added or updated:

* Sadana: https://github.com/BigWigsMods/LittleWigs/commit/be77bcc796db4278253e56b4722fbf8be05ccb17
* Nhallish: https://github.com/BigWigsMods/LittleWigs/commit/2885ac7bed613847a4d2a15f25a9aae8b8e2552f
* Bonemaw: https://github.com/BigWigsMods/LittleWigs/commit/1861115e5c5366a3093714be047eb981525fe03c
* Ner'zhul: https://github.com/BigWigsMods/LittleWigs/commit/894dec21c354853a9d916d0275069332541af5d1
