### ISSUE TITLE
Timewalking Shadowmoon Burial Grounds

### ISSUE THREAD

**Issue by Xruptor** [BigWigsMods/LittleWigs#862]
## Describe the problem

1x ...rlordsOfDraenor/ShadowmoonBurialGrounds/Nhallish.lua:48: attempt to call method 'weBar' (a nil value)
[string "@LittleWigs_WarlordsOfDraenor/ShadowmoonBurialGrounds/Nhallish.lua"]:48: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:566: in function <BigWigs_Core/BossPrototype.lua:532>

Locals:
Skipped (In Encounter)

### What steps will reproduce the problem?

1.  Did timewalking Shadowmoon burial grounds and got this error at Nhallish
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v10.0.20
(it would be nice to have an easier way to view the version in game.  Pershaps on the BigWigs panel?)

### Do you have an error log of what happened?

1x ...rlordsOfDraenor/ShadowmoonBurialGrounds/Nhallish.lua:48: attempt to call method 'weBar' (a nil value)
[string "@LittleWigs_WarlordsOfDraenor/ShadowmoonBurialGrounds/Nhallish.lua"]:48: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:566: in function <BigWigs_Core/BossPrototype.lua:532>

Locals:
Skipped (In Encounter)

**Comment by ntowle** [comment]
Thanks for reporting, fixed by 4cd0c54.
