### ISSUE TITLE
A missing spell of Ruby life pools last boss.

### ISSUE THREAD

**Issue by rstormrage** [BigWigsMods/LittleWigs#864]
I met this problem yesterday when I ran ruby. The ability Flamespit does not show up in the bigwigs dashboard. And this ability is goddamn hurt. And I saw my teammates using dbm could send a msg before the dmg was placed on them.

Ruby Life Pools:
Kyrakka's [ Flamespit](https://www.wowhead.com/spell=381607/flamespit)

**Comment by kpontussvensson** [comment]
I actually think this is the correct spellid: https://www.wowhead.com/spell=381605/flamespit

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/659374744ce4529d3c3e6c7a2b6ab73c8cf1cca0.
