### ISSUE TITLE
Algeth'ar Academy: Astral Bomb tries to set a negative duration timer

### ISSUE THREAD

**Issue by trincasidra** [BigWigsMods/LittleWigs#867]
## Describe the problem
When Spectral Invokers finish casting Astral Bomb, a lua error is thrown because C_Timer.After is called with a negative duration value.

### What steps will reproduce the problem?

1.  Go to Algeth'ar Academy
2.  Kill first 3 bosses
3.  Fight any pack with Spectral Invoker
4.  Wait for the Invoker to cast Astral Bomb

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
v10.0.24
BigWigs: v262

### Do you have an error log of what happened?
```
Message: CombatText:IsVisible(): C_Timer.After requires a non-negative duration
Time: Sun Jan 15 00:35:44 2023
Count: 2
Stack: CombatText:IsVisible(): C_Timer.After requires a non-negative duration
[string "=[C]"]: in function `IsVisible'
[string "@Interface/AddOns/Blizzard_CombatText/Blizzard_CombatText.lua"]:111: in function <...e/AddOns/Blizzard_CombatText/Blizzard_CombatText.lua:110>

Locals: (*temporary) = CombatText {
 0 = <userdata>
 lowHealth = 1
 xDir = -1
 previousMana = <table> {
 }
 unit = "player"
}
```

### Any additional information? (example: WoW language if not English)
WoW Language: Spanish

After some debugging, this error happens when `self:SayCountdown(args.spellId, 3)` is called on line 372 inside the `mod:AstralBombApplied` function in `LittleWigs\Dragonflight\AlgetharAcademy\Trash.lua`.

This ends up calling `boss:SayCountdown` from `BigWigs_Core\BossPrototype.lua`, and on line 2799, `seconds-i` equals to -0.2

I've created [this pull request](https://github.com/BigWigsMods/BigWigs/pull/1332) on the BigWigs repo as well, although I'm not entirely sure that's the best way to solve this issue.

Also, to rule out possible taints from other addons, these are the only addons enabled at the time of testing:
- BigWigs
- BigWigs [Core]
- BigWigs [Options]
- BigWigs [Plugins]
- LittleWigs

**Comment by ntowle** [comment]
Fixed by https://github.com/BigWigsMods/LittleWigs/commit/eb7b39fd9c4c17e4d270b7afc8ed437bec95adb1.

Thanks for reporting.

**Comment by trincasidra** [comment]
Great, thanks!
