### ISSUE TITLE
Melidrussa Chillworn timings are misaligned

### ISSUE THREAD

**Issue by treeant808** [BigWigsMods/LittleWigs#868]
### What steps will reproduce the problem?

1.  fight melidrussa chillworn
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
BigWigs-v262

### Do you have an error log of what happened?
no

**Comment by ntowle** [comment]
I checked logs from the past few weeks as well as pulled it again this morning to confirm the timer and it was accurate, at least in Mythic and Mythic+.

What difficulty were you running the dungeon in?

It's worth noting that the timer for Hailbombs lines up with the end of the Hailbombs cast, as that's when the ground effect for Hailbombs actually spawns, when the alert for Hailbombs fires, and when players actually have to react to Hailbombs (by moving out of the swirlies where they will spawn).

Hailbombs can also be delayed if Melidrussa hits 75%/45% health and starts an Awaken Whelps -> Ice Bulwark -> Frost Overload cycle which will delay any possible Hailbombs cast until after that cycle is complete.

**Comment by ntowle** [comment]
I'm stopping the Hailbombs and Chillstorm timers now when Awaken Whelps starts, and restarting them after Frost Overload is over in https://github.com/BigWigsMods/LittleWigs/commit/e2faa0e98ab3a547aa28431fc227cee82b4c8568.

That should help line up the timers better around those casts (though I did see a decent amount of variance for when Melidrussa resumes her casts after the AW -> IB -> FO cycle is done).
