### ISSUE TITLE
Fenryr Claw Frenzy Timer

### ISSUE THREAD

**Issue by Renascentrelic** [BigWigsMods/LittleWigs#870]
Could you add timers for Fenryrs claw frenzy ability? It's the fights big healing event and it's hard to ramp for it when I don't know when it's coming.

**Comment by ntowle** [comment]
I would consider adding a timer but the ability has such gigantic variance (especially in stage 2) that the timer would just be useless/misleading.

In stage 2 it can be as little as ~7s between casts or as much as ~38s (that I've seen). Unless a pattern is found I think we just have to consider the random interval + zero warning part of the difficulty/design of the fight.

Open to new information if there is indeed a pattern, but I personally haven't been able to find one.

**Comment by ntowle** [comment]
Added stage 1 timers in https://github.com/BigWigsMods/LittleWigs/commit/a498b687e3fd4d8c3e6defb7231e21232857ed75, stage 2 is still too inconsistent for a timer to be useful.
