### ISSUE TITLE
Culling of Stratholme error

### ISSUE THREAD

**Issue by Talimar** [BigWigsMods/LittleWigs#871]
## Describe the problem
See below. Not sure when it triggered, was on hc+.

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
10.0.25

### Do you have an error log of what happened?
2x ..._WrathOfTheLichKing/TheCullingOfStratholme/Trash.lua:63: attempt to call global 'GetNumGossipAvailableQuests' (a nil value)
[string "@LittleWigs_WrathOfTheLichKing/TheCullingOfStratholme/Trash.lua"]:63: in function `?'
[string "@BigWigs_Core/Core.lua"]:59: in function <BigWigs_Core/Core.lua:54>

Locals:
self = <table> {
 instanceId = 595
 RegisterMessage = <function> defined @BigWigs/Loader.lua:919
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:940
 colorOptions = <table> {
 }
 sayCountdowns = <table> {
 }
 soundOptions = <table> {
 }
 db = <table> {
 }
 enableMobs = <table> {
 }
 enabled = true
 toggleOptions = <table> {
 }
 OnBossEnable = <function> defined @LittleWigs_WrathOfTheLichKing/TheCullingOfStratholme/Trash.lua:39
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 toggleDefaults = <table> {
 }
 GOSSIP_SHOW = <function> defined @LittleWigs_WrathOfTheLichKing/TheCullingOfStratholme/Trash.lua:58
 displayName = "Trash"
 name = "BigWigs_Bosses_The Culling of Stratholme Trash"
 SendMessage = <function> defined @BigWigs/Loader.lua:954
 localization = <table> {
 }
 moduleName = "The Culling of Stratholme Trash"
 UnregisterEvent = <function> defined @BigWigs_Core/Core.lua:71
 CHAT_MSG_MONSTER_SAY = <function> defined @LittleWigs_WrathOfTheLichKing/TheCullingOfStratholme/Trash.lua:50
}
mobId = 26527
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumGossipAvailableQuests' (a nil value)"

**Comment by ntowle** [comment]
Looks like there were API changes in patch 3.4.1 which switched WotLK Classic over to more retail-like APIs: https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes
