### ISSUE TITLE
Script ran too long error

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/LittleWigs#882]
## Describe the problem
Was running a key and this error pop up right after the the tree boss and heading over to the tornado mini boss on the platform.

### What steps will reproduce the problem?

1.  n/a
2.  n/a
3.  n/a

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
LittleWigs-v10.0.31.zip

### Do you have an error log of what happened?
1x BigWigs/Loader.lua:1081: script ran too long
[string "@BigWigs/Loader.lua"]:1081: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2874: in function `PlaySound'
[string "@LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua"]:331: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:564: in function <BigWigs_Core/BossPrototype.lua:530>

Locals:
self = <table> {
 DeadlyWinds = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:335
 DetonationSeeds = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:369
 MonotonousLecture = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:317
 colorOptions = <table> {
 }
 enableMobs = <table> {
 }
 ExpelIntruders = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:329
 ArcaneRainSuccess = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:291
 ArcaneRain = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:286
 CallOfTheFlock = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:355
 Riftbreath = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:298
 toggleDefaults = <table> {
 }
 optionHeaders = <table> {
 }
 name = "BigWigs_Bosses_Algeth'ar Academy Trash"
 DisruptingPulse = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:381
 localization = <table> {
 }
 sayCountdowns = <table> {
 }
 enabled = true
 AstralWhirlwindDamage = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:402
 soundOptions = <table> {
 }
 CelestialShieldApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:457
 instanceId = 2526
 StormSlash = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:341
 UnregisterMessage = <function> defined @BigWigs/Loader.lua:1062
 OnBossEnable = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:117
 MysticBlast = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:281
 ManaVoid = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:269
 BronzePledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:237
 GuardianSentryDeath = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:347
 AstralBombRemoved = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:444
 db = <table> {
 }
 SendMessage = <function> defined @BigWigs/Loader.lua:1076
 GreenPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:251
 AstralBomb = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:418
 AstralWhirlwind = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:390
 toggleOptions = <table> {
 }
 BluePledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:244
 Gust = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:360
 RegisterEvent = <function> defined @BigWigs_Core/Core.lua:64
 AstralBombApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:430
 RegisterMessage = <function> defined @BigWigs/Loader.lua:1041
 displayName = "Trash"
 RedPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:258
 ViciousAmbush = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:303
 CelestialShield = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:452
 BlackPledgeApplied = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:230
 GOSSIP_SHOW = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.lua:207
 moduleName = "Algeth'ar Academy Trash"
 UnregisterEvent = <function> defined @BigWigs_Core/Core.lua:71
 CHAT_MSG_MONSTER_SAY = <function> defined @LittleWigs/Dragonflight/AlgetharAcademy/Trash.l

**Comment by ntowle** [comment]
Blizzard changed something this week regarding how long scripts can run in combat. But the call that's being complained about here could not take long enough to trigger this as it's just sending a message to play a sound, there's no logic there. My best guess is you had some other addon or WeakAura that took >200ms to do something. Did you have any other errors at all besides this one?

**Comment by Milky063** [comment]
no just that one error. it was very random. I took the wind jump over to the other platform. when i landed the tank pulled the mini wind boss and just lagged out with that error.
________________________________

**Comment by ntowle** [comment]
Do you have a SSD? Enough RAM? It's possible loading the sound file for the alert took an extra long time for some reason. But I think the error message here is just the symptom rather than the cause.

**Comment by Milky063** [comment]
Installed Physical Memory (RAM)     32.0 GB

Model INTEL SSDPEKNW512G8     
Bytes/Sector      512   

Model Micron Crucial X6 SSD SCSI Disk Device    
Bytes/Sector      512   
________________________________

**Comment by ntowle** [comment]
Those specs should have no problem, did you disconnect or reload your UI at any point in the dungeon before the error occurred?

**Comment by Milky063** [comment]
I dont believe so because it was during a time key run. I would have remembered doing that if i did.
________________________________

**Comment by funkydude** [comment]
Unfortunately this is a problem with your hardware or Windows installation, we will never be able to fix this for you, it will keep happening.

We've asked Blizzard to look into preventing the error happening, but fundamentally the source of the error won't go away:
It's taking too long for the game to load a sound file from your drive.

**Comment by doadin** [comment]
@funkydude  I have had this happen while having the Interface/Addons on a ramdisk(doesnt get much faster, i wouldnt think). I don't think its a storage speed issue. Like others this is the only error I get durrent the play session when it occures.

**Comment by funkydude** [comment]
@doadin Could you please answer the questions I asked above of your system?

**Comment by Milky063** [comment]
Actually you fixed it because this never happen again fyi. gj

**Comment by funkydude** [comment]
> Actually you fixed it because this never happen again fyi. gj

We didn't fix anything. Like has been stated, this is a problem with your system, and we need more info to help Blizz track it down.
If it's not happening anymore, something changed with your system. This could be anything as simple as an anti-virus definition update. We need the information asked above.

**Comment by doadin** [comment]
@funkydude 
I have a 
i5-12600k
32GB 3600 DDR4
windows 11 with Windows Defender(no third party)

**Comment by funkydude** [comment]
@doadin you have your addons folder symlinked and copy it over each time you restart your PC?

**Comment by doadin** [comment]
@funkydude I have only tried ramdisk one time and have not restarted since. But yes its linked and the ramdisk program syncs the folder when starting to the link/drive.

**Comment by Milky063** [comment]
remove my cc i dont need this anymore

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by funkydude** [comment]
@Milky063 We have no control over that. Click the unsubscribe button.

@doadin Do you have an integrated sound card? Do you know what it is? And what driver you are using? (A screenshot of it from device manager might be useful)

**Comment by doadin** [comment]
Yes integrated, Realtek ALC897/ALC892 Codec driver 6.0.9491.1(3/14/2023)

**Comment by Milky063** [comment]
will block this thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by doadin** [comment]
@funkydude I can't confirm this as being a issue, however @ntowle mentioned maybe a weakaura or something takeing up a long time and this error just being a "symptom rather than the cause"  I can remeber that the last time I had this issue I remember seeing in chat(i have the chat setting on to do it and it happened just a little while ago) that I was marking something with "x" and it spam filled my chat. So to try and find what addon is marking, I have run the same instance twice now with same big pulls and with bigwigs marking disabled I makred nothing.(so would seem that bigs wigs was marking) Maybe bigwigs is going through a for loop to find/mark and that is using a lot of resources and thats when the issue occures? idk again I can't confirm this being related at all other than seeing the "[*CHARACTER*] sets x on *mob name*" spamed in chat around that time. No idea if this has happened every time the error has or not. The error is very rare, but im goingt omleave my marking disabled and see what happenes.

**Comment by funkydude** [comment]
You should post the actual error you're seeing @doadin

**Comment by doadin** [comment]
@funkydude  its esentially the same as OP. Just diffrence instance.

```
9x BigWigs_Voice/Core.lua:20: script ran too long
[string "@BigWigs_Voice/Core.lua"]:20: in function <BigWigs_Voice/Core.lua:18>
[string "=[C]"]: ?
[string "@BigWigs/Loader.lua"]:1081: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2898: in function `PlaySound'
[string "@LittleWigs_Legion/HallsOfValor/Trash.lua"]:365: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:589: in function <BigWigs_Core/BossPrototype.lua:555>
```

```
2x BigWigs/Loader.lua:1110: script ran too long
[string "@BigWigs/Loader.lua"]:1110: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2923: in function `PlaySound'
[string "@LittleWigs_Cataclysm/VortexPinnacle/Asaad.lua"]:82: in function `func'
[string "@BigWigs_Core/BossPrototype.lua"]:1090: in function <BigWigs_Core/BossPrototype.lua:1075>

Locals:
Skipped (In Encounter)
```

**Comment by doadin** [comment]
essentially one of those with different instance modules listed.

**Comment by funkydude** [comment]
LittleWigs in general has very little marking, the modules in your errors have none.

I'm assuming you do have BigWigs_Voice installed yes? Do you actually have an error that mentions it?

Also your HoV error doesn't align with the latest version so I'm assuming it's from season 1?

**Comment by doadin** [comment]
@funkydude the marking that as I said could be 100% unrelated just something i noticed since, I have no clue the cause(trying anything I can) and its hard to reproduce the error its pretty rare to happen.

Yes I do have bigwigs voice installed.
