### ISSUE TITLE
Ruby Life Pools: Kyrakka phase 2

### ISSUE THREAD

**Issue by redcatelf** [BigWigsMods/LittleWigs#884]
Could we get a "Phase change soon" heads-up for Phase 2, on the last boss of Ruby Life Pools?

By the looks of it, the Phase 2 transition happens when the average health of the two bosses is 50%.

![image](https://user-images.githubusercontent.com/44137029/219878133-d82b1627-ffc7-43b6-b526-36428d62ffba.png)

**Comment by ntowle** [comment]
It's not average health, it's the first one of them to reach 50% health triggers the phase change. It just takes some seconds after that for Kyrakka to fly over to the right spot.

**Comment by redcatelf** [comment]
Ah. Then maybe we could get a "Phase change soon" heads-up exactly at 50%, or just before? Or even just moving the "Stage 2" message to proc at 50% exactly, rather than when he mounts, would help, cause it lets ranged preposition.

**Comment by ntowle** [comment]
Added in https://github.com/BigWigsMods/LittleWigs/commit/1052017b3eb68ffbfe512c7beacd38b7438505f6.
