### ISSUE TITLE
Halls of Valor Runic Brand Odyn fight conflicting message vs sound alert

### ISSUE THREAD

**Issue by nano1895** [BigWigsMods/LittleWigs#885]
## Describe the problem
On the Odyn fight when the Runic Brand is applied I think the sound alert (top right / bottom right / top left etc.) is conflicting with the emphasized message. I.E. when I get the purple run the sound will say "bottom left" but the text will say "top right" or something like that. 

I'm not a LUA expert but when I go to Odyn.lua I see this code

```
	L[197963] = "|cFF800080Top Right|r (|T1323037:15:15:0:0:64:64:4:60:4:60|t)" -- Boss_OdunRunes_Purple
	L[197964] = "|cFFFFA500Bottom Right|r (|T1323039:15:15:0:0:64:64:4:60:4:60|t)" -- Boss_OdunRunes_Orange
	L[197965] = "|cFFFFFF00Bottom Left|r (|T1323038:15:15:0:0:64:64:4:60:4:60|t)" -- Boss_OdunRunes_Yellow
	L[197966] = "|cFF0000FFTop Left|r (|T1323035:15:15:0:0:64:64:4:60:4:60|t)" -- Boss_OdunRunes_Blue
	L[197967] = "|cFF008000Top|r (|T1323036:15:15:0:0:64:64:4:60:4:60|t)" -- Boss_OdunRunes_Green
```

And I know for sure the audio message I hear for Yellow is definitely not "bottom left" its "top right"

**Comment by ntowle** [comment]
The sound alert is likely from a WeakAura, not from LittleWigs. LittleWigs directions uses North as "top" while a popular WeakAura  with a sound alert for this fight uses South as "top".

**Comment by nano1895** [comment]
Thank you sir for the quick response. That makes sense, I'll try to see where that WA is.

**Comment by nano1895** [comment]
Update: It was indeed a weak aura, took me a while to find but it had conditions that were playing sounds giving directions that were the reverse of little wigs. Thanks all 👍
