### ISSUE TITLE
Court of Stars buff helper bugs

### ISSUE THREAD

**Issue by MysticalOS** [BigWigsMods/LittleWigs#888]
1. Cooking level shouldn't be 800.
2. All the profession icons are wrong with 10.x so they aren't alerting. Grab all the updated texture Ids from (https://github.com/DeadlyBossMods/DBM-Dungeons/blob/master/DBM-Party-Legion/CourtofStars/CoSTrash.lua#L274-L423)
3. None of them actually require level 100 either. from my observation about 50 seems accurate. could even be lower but I just know when my engineering and blacksmithing were at DF 50, they were usable. checking for 100 again alienates available players cause getting to 100 is MUCH harder since it can only be done via work orders over period of time for some professions.

I checked with even low level alts. the DF textures are used/returned by api regardless of profession tier. IE it can be "bfa mining" and still return the new mining icon.

**Comment by MysticalOS** [comment]
PS, you don't have to do anything to be compat with DBM, I did legwork by completely using the BW sync protocol so it's literally seamless. Special thanks to funky for letting me do so. This helps improve both mods.

**Comment by ntowle** [comment]
Do you think the skill requirements might be different in different difficulties? At least on regular Mythic I was able to go learn Tailoring and even at 1 skill it was enough:

![image](https://user-images.githubusercontent.com/20693723/224357477-fda4ea15-e7ab-47f8-aecd-a04b7dc60d26.png)

And actually even 1 skill in Classic Skinning allows me to activate the Skinning one:

![image](https://user-images.githubusercontent.com/20693723/224358752-6ba1f52d-c86d-4420-90a2-c9938f90f9b5.png)

> All the profession icons are wrong with 10.x so they aren't alerting. Grab all the updated texture Ids from (https://github.com/DeadlyBossMods/DBM-Dungeons/blob/master/DBM-Party-Legion/CourtofStars/CoSTrash.lua#L274-L423)

You're having issues with the profession icons alerting? I haven't experienced this:

![image](https://user-images.githubusercontent.com/20693723/224359285-d5a967e4-76ba-462b-a4ee-1357323ba4f5.png)

**Comment by MysticalOS** [comment]
I've had numerous users in my group complain they didn't get alert I had an available profession. when I did code review it was scanning for old profession icon but I was sending the new one in comms. Basically dragonflight revamped profession artwork, so it's got new texture ids now

**Comment by ntowle** [comment]
Updated profession IDs in f90b6629235e7641d66f7b525be9f30c3fa7e8a6, also found that Cooking is a valid profession for Umbral Bloom, that was missing before.

**Comment by MysticalOS** [comment]
👍
and yeah I kept old ids too in case classic sees legion one day, heh.

**Comment by MysticalOS** [comment]
--45278 Haste Buff Court of Stars (cooking/herbalism?)
 --45168 Cooking Interaction buff
 --45332 Engineering interaction to break robots

 --Distractions (to separate boss)
 --45473 Warrior Distraction Court of Stars

Here are some gossip IDs i collected. I stopped collecting though cause I got lazy and went "well, if it isn't the boat, or disguise, or spy interactions. then it's an item interaction"

**Comment by ntowle** [comment]
Yeah I gave up on switching to using gossip IDs when the poison for the first boss had a different ID on my Rogue compared to my alchemist. For the buffs it's probably safe enough to just choose the first (only) option. Just kept the ones I collected in case it's ever needed in the future.

Anyway, thanks for the report. Hopefully everything is syncing well now between DBM and LW.

**Comment by MysticalOS** [comment]
yeah syncing already spot on, and since you synced found ID it was already correct ID, this report was more to fix little wigs, which i talked to several users using LW in my group that were like "yeah professions haven't worked all expansion"

but i'm sure you well know now, users reporting that HERE isn't always great. people used LW for months without saying "btw it's broken". I know the feelings :D
