### ISSUE TITLE
Freezing game during Hyrja fight.

### ISSUE THREAD

**Issue by Shackles70** [BigWigsMods/LittleWigs#890]
1x BigWigs/Loader.lua:1081: script ran too long
[string "@BigWigs/Loader.lua"]:1081: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2898: in function `PlaySound'
[string "@LittleWigs_Legion/HallsOfValor/Hyrja.lua"]:117: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:589: in function <BigWigs_Core/BossPrototype.lua:555>

Locals:
Skipped (In Encounter)

**Comment by ntowle** [comment]
See #882

**Comment by funkydude** [comment]
Please attempt to answer all the questions in the issue linked above.
