### ISSUE TITLE
Dragonflight/Uldaman: Legacy of Tyr/ Missing Trash/ Refti Custodian NPC/abilities missing

### ISSUE THREAD

**Issue by Juanitores** [BigWigsMods/LittleWigs#902]
## Describe the problem
There are no options for the NPC "Refti Custodian" NPCid "184319" in littlewigs.

### What steps will reproduce the problem?

1.  Open /bw
2.  Change the tab to "Dungeon bosses"
3.  Select Uldaman: Legacy of Tyr
4. Change the encounter tab to "Trash"
5. The mob "Refti Custodian" is not listed, thus no abilities can assigned to a certain sound/announce.

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
Bigwigs: v280
Littlewigs: v10.1.10

### Do you have an error log of what happened?
No error log needed.

**Comment by ntowle** [comment]
Fixed by 00fa1228b782ed8bba8b182d5d34450a519f63fd.
