### ISSUE TITLE
Blazing Charge problem

### ISSUE THREAD

**Issue by nanjuekaien1** [BigWigsMods/LittleWigs#904]
Dragonflight's Neltharus copy of Magmatusk's skill Blazing Charge voice does not warn

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
10.1.12

### Do you have an error log of what happened?
[Transcriptor.zip](https://github.com/BigWigsMods/LittleWigs/files/11575195/Transcriptor.zip)

### Any additional information? (example: WoW language if not English)
zhCN

**Comment by ntowle** [comment]
In the log it shows Blazing Charge alert was shown:

```
"<43.42 19:50:43> [BigWigs_Message] Magmatusk#375439#你 炽燃冲锋#blue#135822#true", -- [217]
"<43.42 19:50:43> [BigWigs_StartBar] Magmatusk#375439#炽燃冲锋#26.7#135822#true#nil", -- [218]
"<43.42 19:50:43> [CLEU] SPELL_CAST_SUCCESS#Vehicle-0-3156-2519-21545-181861-0000709BEC#岩浆之牙(63.8%-34.0%)#Player-963-06EE100E#楓聖御雷#375436#炽燃冲锋#nil#nil", -- [219]
```

But you said you didn't get a voice alert? Are you using [BigWigs_Voice](https://github.com/BigWigsMods/BigWigs_Voice)?

**Comment by nanjuekaien1** [comment]
It's the BigWigs_Voice used
You can see it in the statistics Blazing Charge ID: 375431 ;375436 ;375439 ;375455  ，These four IDs.

**Comment by nanjuekaien1** [comment]
`	self:Log("SPELL_CAST_START", "BlazingCharge", 375439)`

Changed here, now voice warning

**Comment by ntowle** [comment]
Thanks for that info. Changing it to use `SPELL_CAST_START` for 375439 would lose the targeting information that's only present on `SPELL_CAST_SUCCESS` for 375436, so LittleWigs would no longer know who is targeted.

Looking into that a bit further it seems like BigWigs does not send the `BigWigs_Voice` message if there is any targeting info:

https://github.com/BigWigsMods/BigWigs/blob/087a14f6a0c230f9ff345ac4911e9db0c095f40f/Core/BossPrototype.lua#L2856-L2881

**Comment by ntowle** [comment]
Will be fixed by https://github.com/BigWigsMods/BigWigs/commit/b13c1d196b2a236a36ae864d66e5e384b1ea5675.

Thanks for the report!

**Comment by nanjuekaien1** [comment]
Thanks, fix bug
