### ISSUE TITLE
Legion Artifact Scenarios not shown in Menu

### ISSUE THREAD

**Issue by hiaws** [BigWigsMods/LittleWigs#930]
## Describe the problem
When I enter a mage tower scenario, I get bars, warnings and everything but I see no option for customization. If I follow the structure of the addon files I would expect it in Dungeon Bosses > Legion > Artifact Scenarios. Searched through various menus without ever finding it. 

### What steps will reproduce the problem?

1.  Open Addon
2.  -> Dungeon Bosses
3.  -> Legion 
4.  No Artifact Scenarios

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
![image](https://github.com/BigWigsMods/LittleWigs/assets/38100039/bf8d89e5-1a98-45ac-864f-2f83a1f88ab5)
![image](https://github.com/BigWigsMods/LittleWigs/assets/38100039/5ec06301-5303-4f4a-ad4a-57755877826e)

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
290 (25cdd90)

**Comment by Justw8** [comment]
Its Broken Shore Mage Tower, it's in your screenshot.
