### ISSUE TITLE
Darkheart Thicket - Oakheart skills are out of sync

### ISSUE THREAD

**Issue by mbackermann** [BigWigsMods/LittleWigs#960]
## Describe the problem

The skills of Darkheart Thicket's boss Oakheart are out of sync, especially Crushing Grip, which is completely out of sync

### What steps will reproduce the problem?

1.  Visit the dungeon and engage with Oakheart
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
10.2.5

### Do you have an error log of what happened?
No

**Comment by ntowle** [comment]
Thanks for the report. Seems Blizzard reworked all the timers since PTR. Fixed in https://github.com/BigWigsMods/LittleWigs/commit/537123ecab9b89946625d2120623ffd6087e51ef.
