### ISSUE TITLE
non-English users to be able to send their say messages in English

### ISSUE THREAD

**Issue by jisamcom** [BigWigsMods/LittleWigs#998]
## Describe the problem
Bigwigs working fine this option, but not littlewigs, can you apply that option to littlewigs also ? 

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
latest version

language if not English)

**Comment by funkydude** [comment]
This works in LittleWigs also, which bosses are you not seeing this on?

**Comment by jisamcom** [comment]
i only see korean messages in m+, like HOI, ULD,..

i will double check this week...

**Comment by funkydude** [comment]
In Uldaman there is only 1 say message for trash, "Trapped in Stone".
In Hallf of Infusion there is no say messages on trash.

Sounds like you've got some WeakAuras doing this?

**Comment by funkydude** [comment]
No response, closing
