### ISSUE TITLE
LittleWigs is Asian on top of BigWigs in English - English Client ( 2 voices at the same time )

### ISSUE THREAD

**Issue by parata412** [BigWigsMods/LittleWigs#999]
## Describe the problem
When i have BigWigs installed ,it works properly - speaks in English and its all fine .
The issue occurs only when i install LitttleWigs + BigWigs - then i have a low volume English voice and High volume Asian Voice ( i guess its Chinese or Japan ) at the same time . Its really bad , as this prevents me from using LittleWigs as i dont understand Asian and i cant reduce/disable its volume to hear what BigWigs actually says . 

### What steps will reproduce the problem?

1.  I have tried to search for settings to adjust the language - unfortunately , i coudlnt find any
2.  
3.  

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
latest

### Do you have an error log of what happened?
None

**Comment by Justw8** [comment]
BigWigs and LittleWigs alone do not have voices/tts enabled by default. This is some plugin you installed. 
Or multiple?

**Comment by funkydude** [comment]
No response, closing
